# IMPORT DATA, PACKAGES, AND FUNCTIONS

## import the relevant functions and packages

In [1]:
import pandas as pd
import numpy as np
import random
import re
from test_case_generator_functions import separate_words_in_name_2,separate_words_in_name_3, special_characters,alphabet, characters_digital

s

In [2]:
df = pd.read_excel('GWU Test Case Type Tracker_ABCNY.XLSX')

C:\Users\jrblu\anaconda3\lib\site-packages\openpyxl\worksheet\_read_only.py:79: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():

In [3]:
bh=df[df['Student']=='Bohao He']
bhin = bh[bh['Entity Type']=='Individual']
bhve = bh[bh['Entity Type']=='Vessel']

In [4]:
bhin

,UID,Theme,Category,Subcategory,Entity Type,Example Original Name,Example Test Case Name,Student,Status,Notes,Unnamed: 10,Team Members,Work Allocation
314,UID-315,Names where Name Parts are Modified,Typos,Typo noise name parts,Individual,"Han, Jang Su",JANG SO HAN,Bohao He,complete,"Noise words include but not limited to = [von,...",NaN,NaN,NaN
316,UID-317,Names where Name Parts are Modified,Typos,Very Short Name,Individual,"Bitar, Ahd",AHD BIRAR,Bohao He,complete,NaN,NaN,NaN,NaN
321,UID-322,Special Characters and Spaces,Addition,>2 special characters added,Individual,"Kovtun, Dmitri",DMI&T#RI K!OVTUN,Bohao He,complete,NaN,NaN,NaN,NaN
324,UID-325,Special Characters and Spaces,Addition,1 special character added,Individual,"Liu, Emily",EMILY LIU@,Bohao He,complete,NaN,NaN,NaN,NaN
426,UID-440,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/DD/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/27/1941,Bohao He,complete,NaN,NaN,NaN,NaN
427,UID-441,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/YY,Individual,"Varela, Wilber",WILBER VARELA 11/57,Bohao He,complete,NaN,NaN,NaN,NaN
428,UID-442,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/1941,Bohao He,complete,NaN,NaN,NaN,NaN
429,UID-443,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in YY/DD/MM,Individual,"Varela, Wilber",WILBER VARELA 57/06/11,Bohao He,complete,NaN,NaN,NaN,NaN
430,UID-444,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in DD/MM/YY,Individual,"Varela, Wilber",WILBER VARELA 06/11/59,Bohao He,complete,NaN,NaN,NaN,NaN
431,UID-445,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in DD/MM/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 27/04/1944,Bohao He,complete,NaN,NaN,NaN,NaN
432,UID-446,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD,Individual,"Varela, Wilber",WILBER VARELA 09/06,Bohao He,complete,NaN,NaN,NaN,NaN
433,UID-447,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD/YY,Individual,"Steiger, Jakob",JAKOB STEIGER 09/27/1944,Bohao He,complete,NaN,NaN,NaN,NaN
434,UID-448,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD/YYYY,Individual,"Varela, Wilber",WILBER VARELA 11/06/1959,Bohao He,complete,NaN,NaN,NaN,NaN
435,UID-449,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/YY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/45,Bohao He,complete,NaN,NaN,NaN,NaN
436,UID-450,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/YYYY,Individual,"Varela, Wilber",WILBER VARELA 11/1959,Bohao He,complete,NaN,NaN,NaN,NaN
437,UID-451,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in YY/DD/MM,Individual,"Steiger, Jakob",JAKOB STEIGER 45/27/04,Bohao He,complete,NaN,NaN,NaN,NaN
438,UID-452,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARELA 1955,Bohao He,complete,NaN,NaN,NaN,NaN
439,UID-453,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in DD-MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 27-04-41,Bohao He,complete,NaN,NaN,NaN,NaN
440,UID-454,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in DD-MM-YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 27-04-1941,Bohao He,complete,NaN,NaN,NaN,NaN
441,UID-455,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD,Individual,"Varela, Wilber",WILBER VARRELA 06-11,Bohao He,complete,NaN,NaN,NaN,NaN
442,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-27-41,Bohao He,complete,NaN,NaN,NaN,NaN
443,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-06-1957,Bohao He,complete,NaN,NaN,NaN,NaN
444,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-41,Bohao He,complete,NaN,NaN,NaN,NaN
445,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-1957,Bohao He,complete,NaN,NaN,NaN,NaN
446,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,"Steiger, Jakob",JAKUB STEIGER 41-27-04,Bohao He,complete,NaN,NaN,NaN,NaN
447,UID-461,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1957,Bohao He,complete,NaN,NaN,NaN,NaN
448,UID-462,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in DD-MM-YY,Individual,"Varela, Wilber",WILBER VARRELA 06-11-59,Bohao He,complete,NaN,NaN,NaN,NaN
449,UID-463,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in DD-MM-YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-27-1943,Bohao He,complete,NaN,NaN,NaN,NaN
450,UID-464,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD,Individual,"Varela, Wilber",WILBER VARRELA 09-11,Bohao He,complete,NaN,NaN,NaN,NaN
451,UID-465,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 06-27-43,Bohao He,complete,NaN,NaN,NaN,NaN
452,UID-466,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 9-06-1959,Bohao He,complete,NaN,NaN,NaN,NaN
453,UID-467,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-44,Bohao He,complete,NaN,NaN,NaN,NaN
454,UID-468,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-1959,Bohao He,complete,NaN,NaN,NaN,NaN
455,UID-469,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in YY-DD-MM,Individual,"Steiger, Jakob",JAKUB STEIGER 45-27-04,Bohao He,complete,NaN,NaN,NaN,NaN
456,UID-470,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1959,Bohao He,complete,NaN,NaN,NaN,NaN
457,UID-471,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in DD/MM/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 27/04/43,Bohao He,complete,NaN,NaN,NaN,NaN
458,UID-472,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in DD/MM/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 06/11/1957,Bohao He,complete,NaN,NaN,NaN,NaN
459,UID-473,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD,Individual,"Steiger, Jakob",JAKUB STEIGER 04/27,Bohao He,complete,NaN,NaN,NaN,NaN
460,UID-474,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD/YY,Individual,"Varela, Wilber",WILBER VARRELA 11/06/57,Bohao He,complete,NaN,NaN,NaN,NaN
461,UID-475,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/27/1941,Bohao He,complete,NaN,NaN,NaN,NaN
462,UID-476,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/YY,Individual,"Varela, Wilber",WILBER VARRELA 11/57,Bohao He,complete,NaN,NaN,NaN,NaN
463,UID-477,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/1941,Bohao He,complete,NaN,NaN,NaN,NaN
464,UID-478,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in YY/DD/MM,Individual,"Varela, Wilber",WILBER VARRELA 57/06/11,Bohao He,complete,NaN,NaN,NaN,NaN
465,UID-479,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in DD/MM/YY,Individual,"Varela, Wilber",WILBER VARRELA 06/11/59,Bohao He,complete,NaN,NaN,NaN,NaN
466,UID-480,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in DD/MM/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 27/04/1944,Bohao He,complete,NaN,NaN,NaN,NaN
467,UID-481,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD,Individual,"Varela, Wilber",WILBER VARRELA 09/06,Bohao He,complete,NaN,NaN,NaN,NaN
468,UID-482,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 09/27/1944,Bohao He,complete,NaN,NaN,NaN,NaN
469,UID-483,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11/06/1959,Bohao He,complete,NaN,NaN,NaN,NaN
470,UID-484,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/45,Bohao He,complete,NaN,NaN,NaN,NaN
471,UID-485,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11/1959,Bohao He,complete,NaN,NaN,NaN,NaN
472,UID-486,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in YY/DD/MM,Individual,"Steiger, Jakob",JAKUB STEIGER 45/27/04,Bohao He,complete,NaN,NaN,NaN,NaN
473,UID-487,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1955,Bohao He,complete,NaN,NaN,NaN,NaN
604,UID-639,Negative Control,No Match,100% false match,Individual,"TUFAYLI, Subhi","Anderson, John",Bohao He,NaN,NaN,NaN,NaN,NaN
605,UID-640,Different Name Parts,Title,1 Title difference,Individual,"AL ZAWAHIRI, Dr. Ayman","AL ZAWAHIRI, Mr. Ayman",Bohao He,NaN,NaN,NaN,NaN,NaN
606,UID-641,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in YYYY,Individual,"ANGULO OROBIO (SEGUNDO), Jose Francisco","ANGULO OROBIO (SEGUNDO), Jose Francisco 1964",Bohao He,NaN,NaN,NaN,NaN,NaN

# TEST CASE TYPE REFERENCE INFORMATION

In [5]:
uid_list_in = list(bhin.UID)
uid_list_ve = list(bhve.UID)
#entity_type_list = ['Country', 'Entity', 'Individual']
#for i in range(440,509):
#    uid_list_in.append('UID-{0}'.format(i)) 
#for j in range(509,549):
#    uid_list_ve.append('UID-{0}'.format(j))
#theme = 'IDs'
#category = list(bhin[bhin['UID']==uid]['Subcategory'])[0]
#sub_category = list(bhin[bhin['UID']==uid]['Subcategory'])[0]
#entity_type = ['Individual','Vessel']

## download the OFAC list from the web

In [6]:
ofac_list_download = pd.read_csv('https://www.treasury.gov/ofac/downloads/sdn.csv', header=None)
ofac_list_download

,0,1,2,3,4,5,6,7,8,9,10,11
0,36,AEROCARIBBEAN AIRLINES,-0-,CUBA,-0-,-0-,-0-,-0-,-0-,-0-,-0-,-0-
1,173,"ANGLO-CARIBBEAN CO., LTD.",-0-,CUBA,-0-,-0-,-0-,-0-,-0-,-0-,-0-,-0-
2,306,BANCO NACIONAL DE CUBA,-0-,CUBA,-0-,-0-,-0-,-0-,-0-,-0-,-0-,a.k.a. 'BNC'.
3,424,BOUTIQUE LA MAISON,-0-,CUBA,-0-,-0-,-0-,-0-,-0-,-0-,-0-,-0-
4,475,CASA DE CUBA,-0-,CUBA,-0-,-0-,-0-,-0-,-0-,-0-,-0-,-0-
...,...,...,...,...,...,...,...,...,...,...,...,...
10998,39704,VISTA CLARA SHIPPING CORPORATION,-0-,SDGT,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Secondary sanctions risk: section 1(b) of Exec...
10999,39709,BUSHEHR PRISON,-0-,CAATSA - IRAN,-0-,-0-,-0-,-0-,-0-,-0-,-0-,Additional Sanctions Information - Subject to ...
11000,39710,"OSTAD, Mohammad Reza",individual,CAATSA - IRAN,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 22 Jun 1975; nationality Iran; Additional ...
11001,39711,"MIRHEYDARY, Mohammad Reza",individual,CAATSA - IRAN,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1956; alt. DOB 1957; POB Iran; nationality...
11002,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
for i in ofac_list_download.columns:
    print(ofac_list_download[i].unique())

['36' '173' '306' ... '39710' '39711' '\x1a']
['AEROCARIBBEAN AIRLINES' 'ANGLO-CARIBBEAN CO., LTD.'
 'BANCO NACIONAL DE CUBA' ... 'OSTAD, Mohammad Reza'
 'MIRHEYDARY, Mohammad Reza' nan]
['-0- ' 'individual' 'vessel' 'aircraft' nan]
['CUBA' 'SDGT' 'SDGT] [SYRIA' 'IRAQ2' 'SDNT' 'IRAN] [SDGT] [IRGC] [IFSR'
 'IRAN] [IRAN-EO13902' 'IRAN] [SDGT] [IFSR' 'FTO] [SDGT'
 'FTO] [SDGT] [SYRIA' 'SDNTK] [FTO] [SDGT' 'SDNTK' 'SDNTK] [SDGT'
 'SDNTK] [ILLICIT-DRUGS-EO14059' 'ZIMBABWE' 'BALKANS' 'DRCONGO'
 'SYRIA] [IRAQ2' 'SYRIA' 'NPWMD] [DPRK2' 'NPWMD'
 'NPWMD] [IFSR] [IRAN-CON-ARMS-EO' 'NPWMD] [IFSR' 'DARFUR' 'SDGT] [NS-PLC'
 'BELARUS'
 'FTO] [SDGT] [NPWMD] [IRGC] [IFSR] [IRAN-HR] [HRIT-IR] [ELECTION-EO13848'
 'SDGT] [NPWMD] [IFSR] [IRAN-CON-ARMS-EO' 'SDGT] [IFSR'
 'FTO] [SDGT] [SYRIA] [IRGC] [IFSR] [IRAN-HR] [ELECTION-EO13848'
 'SDGT] [NPWMD] [IRGC] [IFSR' 'SDGT] [SYRIA] [NPWMD] [IRGC] [IFSR' 'IRAQ3'
 'LEBANON' 'SYRIA] [LEBANON' 'SDGT] [IRAQ3] [IRGC' 'FTO] [SDGT] [SOMALIA'
 'SYRIA] [HRIT-SY' 'SDGT] [CAR' 'SDGT] [IRAQ3'
 'SDGT] [IRAQ3] [IRGC] [IFSR' 'NPWMD] [IFSR] [IRAN-TRA' 'VENEZUELA'
 'IRAN] [SDGT] [IFSR] [IFCA' 'IRAN' 'SDNTK] [TCO] [ILLICIT-DRUGS-EO14059'
 'FTO] [SDGT] [IRAQ3' 'IRAN] [NPWMD] [IFSR' 'SOMALIA'
 'FTO] [SDGT] [NPWMD] [IRGC] [IFSR'
 'SDGT] [NPWMD] [IRGC] [IFSR] [IRAN-HR] [IRAN-EO13876'
 'NPWMD] [IFSR] [IRAN-HR' 'SDGT] [NPWMD] [IRGC] [IFSR] [IRAN-HR'
 'SDGT] [SYRIA] [IFSR] [IRAN-HR] [HRIT-IR] [CYBER2' 'SDGT] [IRGC] [IFSR'
 'DPRK' 'DPRK] [DPRK2' 'SYRIA] [IRAN-HR' 'IRAN-HR' 'SDGT] [IRGC] [IRAN-HR'
 'IRAN] [SDGT] [NPWMD] [IRGC] [IFSR'
 'SDGT] [NPWMD] [IRGC] [IFSR] [IRAN-EO13876' 'LIBYA2' 'SDNTK] [TCO'
 'SYRIA] [SYRIA-EO13894' 'FTO] [SDGT] [IRGC] [IFSR] [IRAN-HR'
 'SYRIA] [IRAN-HR] [IRAN-TRA' 'SYRIA] [IRAN-HR] [HRIT-IR'
 'SDGT] [NPWMD] [IRGC] [IFSR] [IFCA' 'TCO' 'SYRIA] [ISA'
 'SDGT] [NPWMD] [IFSR' 'HRIT-IR' 'SDGT] [SYRIA] [IRGC] [IFSR'
 'IRAN] [SDGT' 'SYRIA] [NPWMD] [IFSR' 'IRAN-TRA' 'NPWMD] [DPRK3'
 'SDGT] [LEBANON' 'MAGNIT' 'IRAN-HR] [IRAN-EO13876' 'IRAN] [IRAN-EO13876'
 'UKRAINE-EO13660' 'UKRAINE-EO13661' 'SOUTH SUDAN'
 'UKRAINE-EO13661] [RUSSIA-EO14024' 'UKRAINE-EO13661] [ELECTION-EO13848'
 'FTO] [SDGT] [DRCONGO' 'CAR' 'UKRAINE-EO13660] [RUSSIA-EO14024'
 'TCO] [RUSSIA-EO14024' 'UKRAINE-EO13662] [RUSSIA-EO14024'
 'UKRAINE-EO13660] [RUSSIA-EO14065' 'YEMEN' 'SYRIA] [FSE-SY' 'DPRK2'
 'UKRAINE-EO13685' 'UKRAINE-EO13662] [VENEZUELA-EO13850'
 'SYRIA] [UKRAINE-EO13662] [RUSSIA-EO14024' 'SDGT] [HIFPAA' 'DPRK3'
 'LIBYA3' 'UKRAINE-EO13685] [PEESA-EO14039'
 'UKRAINE-EO13661] [CYBER2] [ELECTION-EO13848] [RUSSIA-EO14024'
 'MAGNIT] [RUSSIA-EO14024' 'CYBER2' 'CYBER2] [CAATSA - RUSSIA'
 'NPWMD] [CYBER2] [CAATSA - RUSSIA] [RUSSIA-EO14024'
 'BALKANS] [BALKANS-EO14033' 'SDGT] [LIBYA3'
 'UKRAINE-EO13685] [RUSSIA-EO14024' 'UKRAINE-EO13661] [CYBER2'
 'UKRAINE-EO13660] [UKRAINE-EO13661' 'VENEZUELA] [IRAN-CON-ARMS-EO'
 'DPRK4' 'DPRK2] [DPRK4' 'GLOMAG' 'MAGNIT] [GLOMAG' 'IRAN] [IRAN-TRA'
 'SDGT] [IRGC] [IFSR] [HRIT-IR' 'CYBER2] [ELECTION-EO13848'
 'CAATSA - RUSSIA' 'HRIT-IR] [CYBER2' 'UKRAINE-EO13662'
 'UKRAINE-EO13661] [UKRAINE-EO13662' 'NPWMD] [IRGC] [IFSR'
 'GLOMAG] [BURMA-EO14014' 'DPRK3] [DPRK4'
 'SDGT] [IFSR] [IFCA] [IRAN-EO13871' 'IRAN] [SDGT] [IFSR] [IRAN-EO13876'
 'SSIDES' 'IRAN] [SDGT] [NPWMD] [IFSR' 'IRAN] [NPWMD] [IFSR] [IFCA'
 'SDGT] [SYRIA] [IFSR' 'IRAN] [IFCA' 'UKRAINE-EO13661] [UKRAINE-EO13685'
 'IRAN] [IRAN-HR' 'IRAN] [IRAN-EO13871' 'NICARAGUA'
 'NPWMD] [CAATSA - RUSSIA' 'VENEZUELA-EO13850'
 'UKRAINE-EO13661] [CYBER2] [ELECTION-EO13848'
 'SDGT] [IRGC] [IFSR] [IRAN-HR] [SYRIA-EO13894'
 'SDGT] [IRGC] [IFSR] [IRAN-HR' 'HRIT-IR] [ELECTION-EO13848'
 'VENEZUELA-EO13884' 'FTO] [IRGC' 'NICARAGUA] [NICARAGUA-NHRAA'
 'IRAN-EO13876' 'IRAN-EO13846' 'ELECTION-EO13848'
 'SYRIA] [UKRAINE-EO13685' 'MALI-EO13882' 'DPRK3] [DPRK-NKSPEA'
 'SYRIA-EO13894' 'IRGC] [IRAN-HR] [IRAN-EO13876' 'SDGT] [GLOMAG'
 'DPRK3] [CYBER2' 'IRAN-EO13871' 'IRAN-EO13871] [IRAN-EO13876'
 'IFCA] [IRAN-EO13871' 'DPRK2] [DPRK3' 'IRGC] [IFSR] [IRAN-HR'
 'CAATSA - IRAN' 'SYRIA] [SYRIA-CAESAR' 'IFCA' 'HK-EO13936'
 'SDGT] [IFSR] [IRAN-EO13846' 'ILLICIT-DRUGS-EO14059' 'YEMEN] [GLOMAG'
 'NPWMD] [RUSSIA-EO14024' 'CAATSA - RUSSIA] [PEESA'
 'NPWMD] [UKRAINE-EO13661] [RUSSIA-EO14024' 'BURMA-EO14014'
 'NPWMD] [CYBER2] [CAATSA - RUSSIA' 'NPWMD] [CYBER2] [ELECTION-EO13848'
 'UKRAINE-EO13660] [ELECTION-EO13848' 'RUSSIA-EO14024'
 'NPWMD] [CYBER2] [CAATSA - RUSSIA] [ELECTION-EO13848' 'BELARUS-EO14038'
 'PEESA-EO14039' 'ETHIOPIA-EO14046' 'IRGC] [IRAN-HR' 'BALKANS-EO14033'
 'NPWMD] [CYBER2' 'MAGNIT] [GLOMAG] [RUSSIA-EO14024' 'RUSSIA-EO14065'
 'IRGC] [IFSR] [CYBER2' 'UKRAINE-EO13660] [UKRAINE-EO13685'
 'IFSR] [IRAN-HR] [CYBER2' nan]
['-0- ' 'Director of PALESTINE LIBERATION FRONT - ABU ABBAS FACTION'
 "Chief Ideological Figure of ISLAMIC GAMA'AT"
 'Operational and Military Leader of JIHAD GROUP'
 'Chief Ideological Figure of PALESTINIAN ISLAMIC JIHAD - SHIQAQI'
 'Leading Ideological Figure of HIZBALLAH'
 'Secretary General of DEMOCRATIC FRONT FOR THE LIBERATION OF PALESTINE - HAWATMEH FACTION'
 "Military Leader of ISLAMIC GAMA'AT"
 'Secretary General of POPULAR FRONT FOR THE LIBERATION OF PALESTINE - GENERAL COMMAND'
 'Principal Deputy of POPULAR FRONT FOR THE LIBERATION OF PALESTINE - GENERAL COMMAND'
 'Secretary General of Hizballah'
 'Former Secretary General and Current Senior Figure of HIZBALLAH'
 'Political Leader in Amman, Jordan and Damascus, Syria for HAMAS'
 'Secretary General of the PALESTINIAN ISLAMIC JIHAD'
 "Commander of the Faithful ('Amir al-Munineen')"
 'President of the Republic of Zimbabwe'
 'Minister of State for Special Affairs, Land and Resettlement Program'
 'Permanent Secretary, Zimbabwean Ministry of Information and Publicity'
 'Member of Parliament & Central Committee Member' 'Police Commissioner'
 'Minister of Justice, Legal and Parliamentary Affairs'
 'Lt. General, Commander of Zimbabwe Defense Forces'
 'Masvingo Provincial Governor'
 'Minister of Local Government, Public Works and National Housing'
 'Minister of Public Works, Labour and Social Welfare'
 'Minister of Economic Development'
 'Deputy Minister for Youth Development and Employment Creation & Deputy Secretary for Youth Affairs'
 'Member of Parliament for Gokwe Kana' 'Minister of Agriculture'
 'Deputy Speaker of Parliament'
 'Deputy Secretary for Disabled and Disadvantaged'
 'Deputy Minister for Home Affairs'
 'Matebeleland South Provincial Governor & Politburo Secretary for Gender and Culture'
 'Minister of Rural Housing and Social Amenities'
 'Minister of Home Affairs'
 'Member of Parliament for Tsholotsho & Former Minister of Information and Publicity'
 'Deputy Secretary for National Security'
 "Minister of Women's Affairs, Gender and Community Development"
 'Spouse of Robert Mugabe' 'Second Vice President'
 'Non-Constituency Member of Parliament' 'Minister of Finance'
 'Minister of Transport and Communications'
 'Minister of State for National Security'
 'Deputy Minister for Small and Medium Enterprise Development'
 'Politburo Senior Committee Member'
 'Former Director of the Central Intelligence Organization'
 'Deputy Minister of Public Service, Labor and Social Welfare'
 'Minister of Environment and Tourism'
 'Minister of Health and Child Welfare' 'Minister of Defense'
 'Director, Srpska Sume Forestry Company, Sokolac, Bosnia-Herzegovina'
 'Secretary General, IARA Headquarters'
 'IARA South Asia Regional Director' 'IARA Peshwar, Pakistan Director'
 'IARA Middle East Regional Director' 'IARA Representative in Ireland'
 'Doctor' 'Brigadier General; Major General'
 'Chief of Syrian Military Intelligence for Lebanon'
 'Minister of Interior, Syria' 'Director of Syrian Military Intelligence'
 'Deputy Minister of Finance'
 'Deputy Minister of Industry and International Trade'
 'Child of Patrick Chinamasa' 'Chairman of Zimbabwe Electoral Commission'
 "Deputy Minister for Women's Affairs, Gender and Community Development"
 'Deputy Minister of Environment and Tourism' 'Deputy Police Commissioner'
 'Deputy Minister of Foreign Affairs' 'Bulawayo Provincial Governor'
 'Deputy Minister of Information and Publicity'
 'Spouse of Herbert Murerwa'
 'Minister of Youth Development and Employment Creation'
 'Politburo Deputy Commissariat'
 'Minister of Energy and Power Development'
 'Minister of Policy Implementation'
 'Deputy Minister of Science and Technology' 'Spouse of Patrick Chinamasa'
 'Governor of the Reserve Bank of Zimbabwe' 'Spouse of Gideon Gono'
 'Spouse of Patrick Zhuwao' 'Child of Oppah Muchinguri'
 'Spouse of Sydney Sekeramayi'
 'Minister of State for Public and Interactive Affairs'
 'Sheikh and Paramount Chief of the Jalul Tribe in North Darfur'
 'Colonel for the National Movement for Reform and Development (NMRD)'
 'Major General for the Sudan Armed Forces'
 'Commander for the Sudan Liberation Army (SLA)' 'Minister of Justice'
 'Head of the Belarusian State Television and Radio Company (BSTRC); Member of the Upper House of Parliament'
 'Chairman of Belarusian KGB'
 'Colonel in BKGB and Commander of the Special Response Group of the Ministry of the Interior (SOBR)'
 'State Secretary of the Security Council'
 'Head of the Central Commission for Elections and National Referendums (CEC)'
 "Deputy Head of the President's Administration"
 'Head of Presidential Guard' 'Minister of the Interior'
 "Major General; Director, Syria Ba'ath Party Regional Command National Security Bureau"
 'General Manager, Great Lakes Business Company and Compagnie Aerienne des Grands Lacs'
 'former President, Party for Unity and Safeguarding of the Integrity of Congo (PUSIC)'
 'Manager, Great Lakes Business Company and Compagnie Aerienne des Grands Lacs'
 "Founder, National Congress for the People's Defense"
 'President, Forces Democratiques pour la Liberation du Rwanda (FDLR)'
 'Chairman, Justice and Equality Movement; Co-founder, National Redemption Front'
 'Prosecutor General'
 'Commander of the Special Riot Police in Minsk (OMON)'
 'Justice Minister of the Republic of Belarus' 'Minister of Education'
 'Minister of Information'
 'former Minister of Sport and Tourism; former Minister of the Interior'
 'State Minister for Humanitarian Affairs; former State Minister for the Interior; former Coordinator of the Popular Police Forces'
 'Head of Military Intelligence and Security'
 "CHAIRMAN, IRAQI WING OF THE SYRIAN BA'TH PARTY" 'Colonel'
 'Syrian Deputy Vice President for Security Affairs'
 'Brigadier General, Commanding Officer of the Iranian Islamic Revolutionary Guard Corps-Qods Force Ramazan Corps; Deputy Commander of the Ramazan Headquarters; Chief of Staff of the Iraq Crisis Staff'
 'Director General, Central Intelligence Organization' 'MP for Makonde'
 'Dr.' 'RSM leader' "Commander of the Lord's Resistance Army"
 'General Manager - GLOBAL INTERFACE COMPANY INC.' 'Corporate Officer'
 'Major General; Commander FDLR/FOCA' 'FDLR Executive Secretary'
 'Colonel; Commander of FDLR 1st Division'
 'Colonel; Commander, FDLR CO 2nd Division'
 'Brig. General; Deputy Overall Commander FOCA' 'Maulana'
 'Rear Admiral, former Navy Chief of Staff of Guinea-Bissau'
 'Brigadier General, Air Force Chief of Staff of Guinea-Bissau'
 'Brigadier General and Commander of the IRGC Basij Resistance Force; President of the Organization of the Basij of the Oppressed; Chief of the Mobilization of the Oppressed Organization'
 'Brigadier General'
 'Commander-in-Chief, Islamic Revolutionary Guard Corps; Commander, Islamic Revolutionary Guard Corps; Major General; Brigadier Commander'
 'Mufti or Maulana'
 'Deputy Chief, National Police; Deputy Police Chief; Brigadier General'
 'Prosecutor-General of Iran; Hojjatoleslam; Former Minister of Intelligence'
 'Minister of Welfare and Social Security; Former Minister of the Interior and Deputy Commander-in-Chief of the Armed Forces for Law Enforcement'
 'Head, Iranian Anti-Smuggling Task Force; Former Prosecutor-General of Tehran'
 'Minister of Intelligence; Hojjatoleslam'
 'Minister of the Interior; Deputy Commander-in-Chief of the Armed Forces for Law Enforcement'
 'Deputy Commander for Intelligence, Islamic Revolutionary Guard Corps; Hojjatoleslam; Former Commander of the Basij Forces'
 'Lt. Col.' 'FDLR President; FDLR 2nd Vice President; Brigadier General'
 'FDLR/FOCA Chief of Staff; Brigadier General' 'Shaykh' 'Attorney General'
 'Haji'
 'Prosecutor-General of Tehran; General and Revolutionary Prosecutor of Tehran; Tehran Public and Revolution Prosecutor; Tehran Public Prosecutor'
 'Director of the External Security Organization'
 "Secretary of the General People's Committee for Public Works"
 'Defense Minister; Major General'
 'Director of Military Intelligence; Colonel'
 "Secretary of the General People's Committee for Finance and Planning; Secretary of the General People's Committee for Planning and Finance; Finance Minister"
 'Head of Cabinet of Leader Muammar Gaddafi; Chief of Staff; Chairman of Libya Africa Investment Portfolio'
 'General; Director of the Internal Security Office' 'Prime Minister'
 'Major General'
 "Major General; Commander of the Syrian Army's 4th Armored Division"
 'President of the Syrian Arab Republic' 'Vice president'
 'Lieutenant General, Minister of Defense'
 'Major General, Minister of the Interior'
 'Major General, Head of Syrian Military Intelligence'
 'Major General, Director of Political Security Directorate'
 'Commander of IRGC-Qods Force Operations and Training'
 'Head of Iranian Police'
 'Head of Syrian Air Force Intelligence; Major General'
 'Syrian Ambassador to Lebanon'
 'Colonel; Head of Eritrean External Intelligence Operation; Brigadier General'
 'Foreign and Expatriates Minister; Minister for Foreign Affairs'
 'Presidential Political and Media Advisor; Minister, Political and Media Advisor at the Presidency; Doctor'
 "Venezuela's Minister of Urban Agriculture"
 'Head of the Allied Democratic Forces; Commander, Allied Democratic Forces'
 'Professor; Doctor'
 'Lieutenant Commander, IRGC Ground Force; Deputy Commander, IRGC Ground Forces; Brigadier General'
 "Chief of Staff of the Joint Armed Forces of the Islamic Republic of Iran; Chairman of the Armed Forces' Joint Chiefs of Staff; Major General"
 'Commander in Chief, Nduma Defense of Congo, Mayi Mayi Sheka group'
 'Deputy Chief of General Staff of the Syrian Army; Lieutenant General'
 'Islamic Revolutionary Guards Corps Navy Commander'
 'Governor of Central Bank of Syria'
 'Minister of Agriculture and Agrarian Reform'
 'Minister of Higher Education' 'Minister of Economy and Foreign Trade'
 'Minister of Industry' 'Minister of Transport'
 'Minister of Housing and Urban Development' 'Minister of Public Works'
 'Minister of Oil and Mineral Resources' 'Minister of Culture'
 'Minister of Social Affairs and Labor'
 'Minister of State for National Reconciliation Affairs'
 'Minister of State for Environment Affairs'
 'Deputy Prime Minister for Economic Affairs; Minister of Internal Trade and Consumer Protection'
 'Minister of Religious Endowments' 'Minister of Tourism'
 'Minister of Water Resources' 'Minister of Presidential Affairs'
 'Minister of Health' 'Minister of State'
 'Deputy Prime Minister for Services Affairs; Minister of Local Administration'
 'Minister of Electricity' 'Minister of Communications and Technology'
 'Deputy Commander-in-Chief of the Army and the Armed Forces and Minister of Defense'
 'Associate Professor, Department of Computer Engineering, Sharif University of Technology'
 'Minister of Communications and Information Technology; Minister for Information and Communications'
 'Deputy Defense Minister and Dean of Malek Ashtar University'
 'Tanchon Commercial Bank Representative to Beijing, China'
 'Tanchon Commercial Bank Deputy Representative to Beijing, China'
 'Chief Representative, KOMID' 'Deputy Representative, KOMID'
 'Lieutenant Colonel' 'Vice Chairman of the National Defense Commission'
 'Tanchon Commercial Bank Representative'
 'Chairman, Second Economic Committee' 'Managing Director, TESA'
 'Chairman & Director, Naftiran Intertrade Co. (NICO) Sarl; Chairman & Director, Naft Iran Intertrade Company Ltd.; Director, Hong Kong Intertrade Company'
 'Finance Director, National Iranian Oil Company; Director, Hong Kong Intertrade Company; Director, Petro Suisse Intertrade Company'
 'Managing Director, Asia Energy General Trading'
 'Managing Director, Petro Suisse Intertrade Company'
 "Security Deputy of Supreme Leader; Member of the Leader's Planning Chamber; Head of Security of Supreme Leader's Office; Deputy Chief of Staff of the Supreme Leader's Office"
 'External Affairs Bureau Chief, General Bureau of Atomic Energy'
 'Treasurer, Daedong Credit Bank'
 'Managing Director, Sima General Trading'
 'Director, NIOC International Affairs (London) Ltd.'
 'Director, NIOC International Affairs (London) Ltd.; Director of International Affairs, NIOC'
 'Director, Iranian Oil Company (U.K.) Ltd.'
 'Managing Director, Iranian Oil Company (U.K.) Ltd.'
 'Minister of Social Affairs' 'Minister of Labor'
 'Brigadier General; Syrian Presidential Advisor' 'Mulawi'
 'Maulawi; Mullah' 'Former President of Ukraine'
 'Deputy Prime Minister of the Russian Federation'
 "Commander, Presidential Guard Unit; Major General, Sudan People's Liberation Army"
 'Presidential Aide' 'Presidential Advisor'
 'Member of the Federation Council of the Federal Assembly of the Russian Federation'
 'Member of the State Duma of the Federal Assembly of the Russian Federation'
 'Chairman of the Security and Defense Federation Council of the Russian Federation'
 'President of OJSC Russian Railways'
 'Deputy Speaker of the State Duma of the Russian Federation'
 'Deputy Speaker of the Federation Council of the Russian Federation; Chairman of the Council of the Federation Budget and Financial Markets Committee'
 'Member of the Committee on Culture, Science, and Information, Federation Council of the Russian Federation'
 'First Deputy Chairman of the Committee on Parliamentary Issues'
 'Aide to the President of the Russian Federation'
 'Mayor of Sevastopol; Chairman of the Coordination Council for the Establishment of the Sevastopol Municipal Administration'
 'Lieutenant General; Chief of the Main Directorate of the General Staff (GRU); Deputy Chief of the General Staff'
 'First Deputy Chief of Staff of the Presidential Executive Office; First Deputy Head of Presidential Administration; First Deputy Presidential Chief of Staff'
 'Director of the Federal Drug Control Service of the Russian Federation (FSKN)'
 'Speaker of the State Duma of the Federal Assembly of the Russian Federation; Member of Russian Security Council'
 'Head of the Crimean SBU (Security Service of Ukraine)'
 'Former President of the Central African Republic'
 'General; Former Minister of Public Security' 'General'
 'Director of the Federal Protective Service of the Russian Federation; Army General'
 'Former First Deputy Prime Minister of Ukraine'
 'Deputy Chairman of the Council of Ministers of Crimea; Crimean Deputy Prime Minister'
 'Counselor to the Speaker of the Crimean Rada'
 'Chair of the Sevastopol Electoral Commission'
 'Chair of the Crimea Electoral Commission'
 'Former Prime Minister of Ukraine'
 'Russian Presidential Envoy to the Crimean District; Member of the Russian Security Council'
 'Registrar General' 'Managing Director' 'Commercial Director'
 'Chairman of the Management Committee, Tempbank'
 'Acting Governor of Sevastopol' 'Minister for Crimean Affairs'
 'Head of the Office of the Federal Migration Service in the City of Sevastopol'
 'Commander of the Fifth Service of the FSB; Commander of the Service for Operational Information and International Communications of the FSB; FSB Colonel General; Colonel-General'
 'President and Chief Executive Officer, Stars Group Holding'
 'General Manager, Unique Stars Mobile Phones LLC'
 'General Manager, Stars International Ltd' 'Prosecutor of Crimea'
 "Major General; Sudan People's Liberation Army Third Division Commander"
 'Maulana; Moulana; Qari' 'Engineer'

In [8]:
#select rows contain rob
ofac_list_download_dob=ofac_list_download[ofac_list_download[11].str.contains('DOB')==True]

In [9]:
ofac_list_download_dob

,0,1,2,3,4,5,6,7,8,9,10,11
53,2674,"ABBAS, Abu",individual,SDGT,Director of PALESTINE LIBERATION FRONT - ABU A...,-0-,-0-,-0-,-0-,-0-,-0-,DOB 10 Dec 1948; Director of PALESTINE LIBERAT...
54,2675,"AL RAHMAN, Shaykh Umar Abd",individual,SDGT,Chief Ideological Figure of ISLAMIC GAMA'AT,-0-,-0-,-0-,-0-,-0-,-0-,DOB 03 May 1938; POB Egypt; Chief Ideological ...
55,2676,"AL ZAWAHIRI, Dr. Ayman",individual,SDGT,Operational and Military Leader of JIHAD GROUP,-0-,-0-,-0-,-0-,-0-,-0-,"DOB 19 Jun 1951; POB Giza, Egypt; Passport 108..."
56,2677,"AL-ZOMOR, Abboud Abdul Latif Hassan",individual,SDGT,-0-,-0-,-0-,-0-,-0-,-0-,-0-,"DOB 19 Apr 1947; POB Nahia, Giza, Egypt; natio..."
57,2678,"AWDA, Abd Al Aziz",individual,SDGT,Chief Ideological Figure of PALESTINIAN ISLAMI...,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1946; Chief Ideological Figure of PALESTIN...
...,...,...,...,...,...,...,...,...,...,...,...,...
10978,39680,"PIRI, Morteza",individual,IRAN-HR,Warden of Zahedan Central Prison,-0-,-0-,-0-,-0-,-0-,-0-,"DOB 05 Jul 1977; POB Zabol, Sistan and Baluchi..."
10989,39694,"KHOSRAVI, Mohammad Hossein",individual,IRAN-HR,Director-General of Sistan and Baluchistan Pro...,-0-,-0-,-0-,-0-,-0-,-0-,"DOB 23 Sep 1974; POB Birjand, South Khorasan P..."
10992,39697,"FAZZONE, Gregorio",individual,SDGT,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 13 Nov 1959; alt. DOB 31 Dec 1959; nationa...
11000,39710,"OSTAD, Mohammad Reza",individual,CAATSA - IRAN,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 22 Jun 1975; nationality Iran; Additional ...
11001,39711,"MIRHEYDARY, Mohammad Reza",individual,CAATSA - IRAN,-0-,-0-,-0-,-0-,-0-,-0-,-0-,DOB 1956; alt. DOB 1957; POB Iran; nationality...

In [10]:
ofac_list = ofac_list_download[[0,1,2,11]]
ofac_list.columns = ['uid', 'name', 'entity_type','DOB']
ofac_list_dob = ofac_list[ofac_list['DOB'].str.contains('DOB')==True]
#business = list(ofac_list.iloc[0])[2]
#ofac_list['entity_type'] = ofac_list['entity_type'].apply(lambda x:'Business' if x==business else x)

In [11]:
ofac_list

,uid,name,entity_type,DOB
0,36,AEROCARIBBEAN AIRLINES,-0-,-0-
1,173,"ANGLO-CARIBBEAN CO., LTD.",-0-,-0-
2,306,BANCO NACIONAL DE CUBA,-0-,a.k.a. 'BNC'.
3,424,BOUTIQUE LA MAISON,-0-,-0-
4,475,CASA DE CUBA,-0-,-0-
...,...,...,...,...
10998,39704,VISTA CLARA SHIPPING CORPORATION,-0-,Secondary sanctions risk: section 1(b) of Exec...
10999,39709,BUSHEHR PRISON,-0-,Additional Sanctions Information - Subject to ...
11000,39710,"OSTAD, Mohammad Reza",individual,DOB 22 Jun 1975; nationality Iran; Additional ...
11001,39711,"MIRHEYDARY, Mohammad Reza",individual,DOB 1956; alt. DOB 1957; POB Iran; nationality...
11002,,NaN,NaN,NaN

In [12]:
ofac_list_dob.iloc[20]['DOB'].split(';')

['DOB 06 Nov 1966',
 ' Cedula No. 72139939 (Colombia)',
 ' Passport T705915 (Colombia)',
 ' alt. Passport AC143719 (Colombia).']

In [13]:
ofac_list['entity_type'].value_counts()

individual    5756
-0-           4434
vessel         526
aircraft       286
Name: entity_type, dtype: int64

# FILTER FOR THE REQUIREMENTS OF THE TEST CASE TYPE

## filter for the requirements of the specific test case type

In [14]:
ofac_list_filtered_in = ofac_list[(ofac_list.entity_type == 'individual')] # only evaluate individuals
#ofac_list_filtered_in = ofac_list_filtered_in[(ofac_list_filtered_in.name.str.count(' ') < 3)]

In [15]:
ofac_list_filtered_ve = ofac_list[(ofac_list.entity_type == 'vessel')] # only evaluate Vessels

# CREATE THE TEST CASES

## create blank final test cases table

In [16]:
final_test_cases = pd.DataFrame(columns=['UID', 'Theme','Category','Sub-category','Entity-Type','Test Case ID' , 'OFAC List UID', 'Original Name','Test Case Name'])
final_test_cases

Empty DataFrame
Columns: [UID, Theme, Category, Sub-category, Entity-Type, Test Case ID, OFAC List UID, Original Name, Test Case Name]
Index: []

In [17]:
def uid_info(uid):
    theme = list(bhin[bhin['UID']==uid]['Theme'])[0]
    category = list(bhin[bhin['UID']==uid]['Category'])[0]
    sub_category = list(bhin[bhin['UID']==uid]['Subcategory'])[0]
    entity_type = ['Individual','Vessel']
    return[theme,category,sub_category,entity_type]

# UID-456

In [18]:
bhin

,UID,Theme,Category,Subcategory,Entity Type,Example Original Name,Example Test Case Name,Student,Status,Notes,Unnamed: 10,Team Members,Work Allocation
314,UID-315,Names where Name Parts are Modified,Typos,Typo noise name parts,Individual,"Han, Jang Su",JANG SO HAN,Bohao He,complete,"Noise words include but not limited to = [von,...",NaN,NaN,NaN
316,UID-317,Names where Name Parts are Modified,Typos,Very Short Name,Individual,"Bitar, Ahd",AHD BIRAR,Bohao He,complete,NaN,NaN,NaN,NaN
321,UID-322,Special Characters and Spaces,Addition,>2 special characters added,Individual,"Kovtun, Dmitri",DMI&T#RI K!OVTUN,Bohao He,complete,NaN,NaN,NaN,NaN
324,UID-325,Special Characters and Spaces,Addition,1 special character added,Individual,"Liu, Emily",EMILY LIU@,Bohao He,complete,NaN,NaN,NaN,NaN
426,UID-440,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/DD/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/27/1941,Bohao He,complete,NaN,NaN,NaN,NaN
427,UID-441,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/YY,Individual,"Varela, Wilber",WILBER VARELA 11/57,Bohao He,complete,NaN,NaN,NaN,NaN
428,UID-442,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/1941,Bohao He,complete,NaN,NaN,NaN,NaN
429,UID-443,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in YY/DD/MM,Individual,"Varela, Wilber",WILBER VARELA 57/06/11,Bohao He,complete,NaN,NaN,NaN,NaN
430,UID-444,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in DD/MM/YY,Individual,"Varela, Wilber",WILBER VARELA 06/11/59,Bohao He,complete,NaN,NaN,NaN,NaN
431,UID-445,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in DD/MM/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 27/04/1944,Bohao He,complete,NaN,NaN,NaN,NaN
432,UID-446,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD,Individual,"Varela, Wilber",WILBER VARELA 09/06,Bohao He,complete,NaN,NaN,NaN,NaN
433,UID-447,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD/YY,Individual,"Steiger, Jakob",JAKOB STEIGER 09/27/1944,Bohao He,complete,NaN,NaN,NaN,NaN
434,UID-448,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD/YYYY,Individual,"Varela, Wilber",WILBER VARELA 11/06/1959,Bohao He,complete,NaN,NaN,NaN,NaN
435,UID-449,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/YY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/45,Bohao He,complete,NaN,NaN,NaN,NaN
436,UID-450,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/YYYY,Individual,"Varela, Wilber",WILBER VARELA 11/1959,Bohao He,complete,NaN,NaN,NaN,NaN
437,UID-451,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in YY/DD/MM,Individual,"Steiger, Jakob",JAKOB STEIGER 45/27/04,Bohao He,complete,NaN,NaN,NaN,NaN
438,UID-452,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARELA 1955,Bohao He,complete,NaN,NaN,NaN,NaN
439,UID-453,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in DD-MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 27-04-41,Bohao He,complete,NaN,NaN,NaN,NaN
440,UID-454,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in DD-MM-YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 27-04-1941,Bohao He,complete,NaN,NaN,NaN,NaN
441,UID-455,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD,Individual,"Varela, Wilber",WILBER VARRELA 06-11,Bohao He,complete,NaN,NaN,NaN,NaN
442,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-27-41,Bohao He,complete,NaN,NaN,NaN,NaN
443,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-06-1957,Bohao He,complete,NaN,NaN,NaN,NaN
444,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-41,Bohao He,complete,NaN,NaN,NaN,NaN
445,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-1957,Bohao He,complete,NaN,NaN,NaN,NaN
446,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,"Steiger, Jakob",JAKUB STEIGER 41-27-04,Bohao He,complete,NaN,NaN,NaN,NaN
447,UID-461,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1957,Bohao He,complete,NaN,NaN,NaN,NaN
448,UID-462,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in DD-MM-YY,Individual,"Varela, Wilber",WILBER VARRELA 06-11-59,Bohao He,complete,NaN,NaN,NaN,NaN
449,UID-463,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in DD-MM-YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-27-1943,Bohao He,complete,NaN,NaN,NaN,NaN
450,UID-464,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD,Individual,"Varela, Wilber",WILBER VARRELA 09-11,Bohao He,complete,NaN,NaN,NaN,NaN
451,UID-465,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 06-27-43,Bohao He,complete,NaN,NaN,NaN,NaN
452,UID-466,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 9-06-1959,Bohao He,complete,NaN,NaN,NaN,NaN
453,UID-467,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-44,Bohao He,complete,NaN,NaN,NaN,NaN
454,UID-468,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-1959,Bohao He,complete,NaN,NaN,NaN,NaN
455,UID-469,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in YY-DD-MM,Individual,"Steiger, Jakob",JAKUB STEIGER 45-27-04,Bohao He,complete,NaN,NaN,NaN,NaN
456,UID-470,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1959,Bohao He,complete,NaN,NaN,NaN,NaN
457,UID-471,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in DD/MM/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 27/04/43,Bohao He,complete,NaN,NaN,NaN,NaN
458,UID-472,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in DD/MM/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 06/11/1957,Bohao He,complete,NaN,NaN,NaN,NaN
459,UID-473,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD,Individual,"Steiger, Jakob",JAKUB STEIGER 04/27,Bohao He,complete,NaN,NaN,NaN,NaN
460,UID-474,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD/YY,Individual,"Varela, Wilber",WILBER VARRELA 11/06/57,Bohao He,complete,NaN,NaN,NaN,NaN
461,UID-475,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/27/1941,Bohao He,complete,NaN,NaN,NaN,NaN
462,UID-476,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/YY,Individual,"Varela, Wilber",WILBER VARRELA 11/57,Bohao He,complete,NaN,NaN,NaN,NaN
463,UID-477,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/1941,Bohao He,complete,NaN,NaN,NaN,NaN
464,UID-478,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in YY/DD/MM,Individual,"Varela, Wilber",WILBER VARRELA 57/06/11,Bohao He,complete,NaN,NaN,NaN,NaN
465,UID-479,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in DD/MM/YY,Individual,"Varela, Wilber",WILBER VARRELA 06/11/59,Bohao He,complete,NaN,NaN,NaN,NaN
466,UID-480,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in DD/MM/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 27/04/1944,Bohao He,complete,NaN,NaN,NaN,NaN
467,UID-481,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD,Individual,"Varela, Wilber",WILBER VARRELA 09/06,Bohao He,complete,NaN,NaN,NaN,NaN
468,UID-482,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 09/27/1944,Bohao He,complete,NaN,NaN,NaN,NaN
469,UID-483,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11/06/1959,Bohao He,complete,NaN,NaN,NaN,NaN
470,UID-484,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/45,Bohao He,complete,NaN,NaN,NaN,NaN
471,UID-485,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11/1959,Bohao He,complete,NaN,NaN,NaN,NaN
472,UID-486,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in YY/DD/MM,Individual,"Steiger, Jakob",JAKUB STEIGER 45/27/04,Bohao He,complete,NaN,NaN,NaN,NaN
473,UID-487,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1955,Bohao He,complete,NaN,NaN,NaN,NaN
604,UID-639,Negative Control,No Match,100% false match,Individual,"TUFAYLI, Subhi","Anderson, John",Bohao He,NaN,NaN,NaN,NaN,NaN
605,UID-640,Different Name Parts,Title,1 Title difference,Individual,"AL ZAWAHIRI, Dr. Ayman","AL ZAWAHIRI, Mr. Ayman",Bohao He,NaN,NaN,NaN,NaN,NaN
606,UID-641,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in YYYY,Individual,"ANGULO OROBIO (SEGUNDO), Jose Francisco","ANGULO OROBIO (SEGUNDO), Jose Francisco 1964",Bohao He,NaN,NaN,NaN,NaN,NaN

In [19]:
def month_dict():
    dic = {'Jan':'01','Feb':'02','Mar':'03',
           'Apr':'04','May':'05','Jun':'06',
           'Jul':'07','Aug':'08','Sep':'09',
           'Oct':'10','Nov':'11','Dec':'12'}
    return dic

In [20]:
ofac_list_dob_filtered = ofac_list_dob.copy()
#extract date of birth
ofac_list_dob_filtered['DOB']=ofac_list_dob_filtered['DOB'].apply(lambda x : (x.split(';')[0])[4:])
ofac_list_dob_filtered['DOB']=ofac_list_dob_filtered['DOB'].apply(lambda x : (x.split('to')[0]) if re.search('to',x) else x)
for i in month_dict().keys():
    ofac_list_dob_filtered['DOB']=ofac_list_dob_filtered['DOB'].apply(lambda x : re.sub(i,month_dict()[i],x) if re.search(i,x) else x)
ofac_list_dob_filtered['DOB']=ofac_list_dob_filtered['DOB'].apply(lambda x : (x.split('circa')[1]) if re.search('circa',x) else x)

In [21]:
count=[]
for i in range(len(ofac_list_dob_filtered)):
    count.append(len(ofac_list_dob_filtered.iloc[i]['DOB'].split(' ')))
ofac_list_dob_filtered['count'] = ofac_list_dob_filtered['DOB'].apply(lambda x:len(x.split(' ')))

In [22]:
ofac_list_dob_filtered

,uid,name,entity_type,DOB,count
53,2674,"ABBAS, Abu",individual,10 12 1948,3
54,2675,"AL RAHMAN, Shaykh Umar Abd",individual,03 05 1938,3
55,2676,"AL ZAWAHIRI, Dr. Ayman",individual,19 06 1951,3
56,2677,"AL-ZOMOR, Abboud Abdul Latif Hassan",individual,19 04 1947,3
57,2678,"AWDA, Abd Al Aziz",individual,1946,1
...,...,...,...,...,...
10978,39680,"PIRI, Morteza",individual,05 07 1977,3
10989,39694,"KHOSRAVI, Mohammad Hossein",individual,23 09 1974,3
10992,39697,"FAZZONE, Gregorio",individual,13 11 1959,3
11000,39710,"OSTAD, Mohammad Reza",individual,22 06 1975,3
11001,39711,"MIRHEYDARY, Mohammad Reza",individual,1956,1

In [23]:
ofac_list_dob_mdy = ofac_list_dob_filtered.copy()
ofac_list_dob_my = ofac_list_dob_filtered.copy()
#ofac_list_dob_mdy = ofac_list_dob_filtered[ofac_list_dob_filtered['count']==3]
ofac_list_dob_mdy['DOB']=ofac_list_dob_mdy['DOB'].apply(lambda x:re.sub(' ','/',x))
ofac_list_dob_mdy

,uid,name,entity_type,DOB,count
53,2674,"ABBAS, Abu",individual,10/12/1948,3
54,2675,"AL RAHMAN, Shaykh Umar Abd",individual,03/05/1938,3
55,2676,"AL ZAWAHIRI, Dr. Ayman",individual,19/06/1951,3
56,2677,"AL-ZOMOR, Abboud Abdul Latif Hassan",individual,19/04/1947,3
57,2678,"AWDA, Abd Al Aziz",individual,1946,1
...,...,...,...,...,...
10978,39680,"PIRI, Morteza",individual,05/07/1977,3
10989,39694,"KHOSRAVI, Mohammad Hossein",individual,23/09/1974,3
10992,39697,"FAZZONE, Gregorio",individual,13/11/1959,3
11000,39710,"OSTAD, Mohammad Reza",individual,22/06/1975,3
11001,39711,"MIRHEYDARY, Mohammad Reza",individual,1956,1

In [24]:
ofac_list_dob_mmdy = ofac_list_dob_mdy[ofac_list_dob_mdy['DOB'].str.count('/')==2]
ofac_list_dob_mmdy['DOB']=ofac_list_dob_mmdy['DOB'].apply(lambda x:x[3:5]+'/'+x[0:2]+'/'+x[8:])
ofac_list_dob_mmdy

C:\Users\jrblu\AppData\Local\Temp\ipykernel_26244\2573640099.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ofac_list_dob_mmdy['DOB']=ofac_list_dob_mmdy['DOB'].apply(lambda x:x[3:5]+'/'+x[0:2]+'/'+x[8:])

         uid                                 name entity_type       DOB  count
53      2674                           ABBAS, Abu  individual  12/10/48      3
54      2675           AL RAHMAN, Shaykh Umar Abd  individual  05/03/38      3
55      2676               AL ZAWAHIRI, Dr. Ayman  individual  06/19/51      3
56      2677  AL-ZOMOR, Abboud Abdul Latif Hassan  individual  04/19/47      3
60      2682          ISLAMBOULI, Mohammad Shawqi  individual  01/15/55      3
...      ...                                  ...         ...       ...    ...
10974  39676                         FATHI, Murad  individual  05/20/71      3
10978  39680                        PIRI, Morteza  individual  07/05/77      3
10989  39694           KHOSRAVI, Mohammad Hossein  individual  09/23/74      3
10992  39697                    FAZZONE, Gregorio  individual  11/13/59      3
11000  39710                 OSTAD, Mohammad Reza  individual  06/22/75      3

[4754 rows x 5 columns]

In [25]:
final_test_cases = pd.DataFrame(columns=['UID', 'Theme','Category','Sub-category','Entity-Type','Test Case ID' , 'OFAC List UID', 'Original Name','Test Case Name'])
uid='UID-456'
theme = list(bhin[bhin['UID']==uid]['Theme'])[0]
category = list(bhin[bhin['UID']==uid]['Category'])[0]
sub_category = list(bhin[bhin['UID']==uid]['Subcategory'])[0]
entity_type = ['Individual','Vessel']
ofac_list_sampled = ofac_list_dob_mmdy.sample(n = 10)
for index, row in ofac_list_sampled.iterrows():
    original_name = row['name']
    name_pice = row['name'].split(',')
    final_test_name =''
    while len(name_pice)>0:
        n=random.choice(name_pice)
        final_test_name=final_test_name+' '+n
        name_pice.remove(n)
        final_test_name=final_test_name.upper()
    
    final_test_cases.loc[len(final_test_cases)] = [uid, theme, category, sub_category, entity_type[0], uid + ' - ' + str(index), row['uid'], row['name'], final_test_name+' '+row['DOB']] # append to the dataframe

final_test_cases

,UID,Theme,Category,Sub-category,Entity-Type,Test Case ID,OFAC List UID,Original Name,Test Case Name
0,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 9699,35675,"MAKAROV, Vyatscheslav Serafimovich",MAKAROV VYATSCHESLAV SERAFIMOVICH 05/07/55
1,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 260,7167,"FREGOSO AMEZQUITA, Maria Antonieta",FREGOSO AMEZQUITA MARIA ANTONIETA 10/29/52
2,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 322,7256,"KISHK, Samir",SAMIR KISHK 05/14/55
3,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 10978,39680,"PIRI, Morteza",PIRI MORTEZA 07/05/77
4,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 1422,10322,"CASTELLANOS SANCHEZ, Federico Ernesto",FEDERICO ERNESTO CASTELLANOS SANCHEZ 01/11/47
5,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 852,8294,"RUPRAH, Sanjivan Singh",SANJIVAN SINGH RUPRAH 08/09/66
6,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 8366,31124,"KRIVORUCHKO, Aleksei Yurievich",ALEKSEI YURIEVICH KRIVORUCHKO 07/17/75
7,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 462,7662,"BORAVCANIN, Ljubomir",BORAVCANIN LJUBOMIR 02/27/60
8,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 1510,10481,"SOLEIMANI, Qasem",QASEM SOLEIMANI 03/11/57
9,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 7695,28700,"GHASEMZADEH, Mehdi",GHASEMZADEH MEHDI 09/21/81

In [26]:
#uid='UID-451'
#theme = list(bhin[bhin['UID']==uid]['Theme'])[0]
#category = list(bhin[bhin['UID']==uid]['Category'])[0]
#sub_category = list(bhin[bhin['UID']==uid]['Subcategory'])[0]
#entity_type = ['Individual','Vessel']
#ofac_list_sampled = ofac_list_dob_mdy.sample(n = 10)
#for index, row in ofac_list_sampled.iterrows():
#    original_name = row['name']
#    name_pice = row['name'].split(',')
#    final_test_name =''
#    while len(name_pice)>0:
#        n=random.choice(name_pice)
#        final_test_name=final_test_name+' '+n
#        name_pice.remove(n)
#        final_test_name=final_test_name.upper()
#    
#    final_test_cases.loc[len(final_test_cases)] = [uid, theme, category, sub_category, entity_type[0], uid + ' - ' + str(index), row['uid'], row['name'], final_test_name+' '+row['DOB']] # append to the dataframe
#
#final_test_cases

In [27]:
ofac_list_dob_mdy

,uid,name,entity_type,DOB,count
53,2674,"ABBAS, Abu",individual,10/12/1948,3
54,2675,"AL RAHMAN, Shaykh Umar Abd",individual,03/05/1938,3
55,2676,"AL ZAWAHIRI, Dr. Ayman",individual,19/06/1951,3
56,2677,"AL-ZOMOR, Abboud Abdul Latif Hassan",individual,19/04/1947,3
57,2678,"AWDA, Abd Al Aziz",individual,1946,1
...,...,...,...,...,...
10978,39680,"PIRI, Morteza",individual,05/07/1977,3
10989,39694,"KHOSRAVI, Mohammad Hossein",individual,23/09/1974,3
10992,39697,"FAZZONE, Gregorio",individual,13/11/1959,3
11000,39710,"OSTAD, Mohammad Reza",individual,22/06/1975,3
11001,39711,"MIRHEYDARY, Mohammad Reza",individual,1956,1

# UID-457

In [28]:
ofac_list_dob_mmdy = ofac_list_dob_mdy[ofac_list_dob_mdy['DOB'].str.count('/')==2]
ofac_list_dob_mmdy['DOB']=ofac_list_dob_mmdy['DOB'].apply(lambda x:x[3:5]+'/'+x[0:2]+'/'+x[6:])
ofac_list_dob_mmdy

C:\Users\jrblu\AppData\Local\Temp\ipykernel_26244\1039185723.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ofac_list_dob_mmdy['DOB']=ofac_list_dob_mmdy['DOB'].apply(lambda x:x[3:5]+'/'+x[0:2]+'/'+x[6:])

,uid,name,entity_type,DOB,count
53,2674,"ABBAS, Abu",individual,12/10/1948,3
54,2675,"AL RAHMAN, Shaykh Umar Abd",individual,05/03/1938,3
55,2676,"AL ZAWAHIRI, Dr. Ayman",individual,06/19/1951,3
56,2677,"AL-ZOMOR, Abboud Abdul Latif Hassan",individual,04/19/1947,3
60,2682,"ISLAMBOULI, Mohammad Shawqi",individual,01/15/1955,3
...,...,...,...,...,...
10974,39676,"FATHI, Murad",individual,05/20/1971,3
10978,39680,"PIRI, Morteza",individual,07/05/1977,3
10989,39694,"KHOSRAVI, Mohammad Hossein",individual,09/23/1974,3
10992,39697,"FAZZONE, Gregorio",individual,11/13/1959,3
11000,39710,"OSTAD, Mohammad Reza",individual,06/22/1975,3

In [29]:
#final_test_cases = pd.DataFrame(columns=['UID', 'Theme','Category','Sub-category','Entity-Type','Test Case ID' , 'OFAC List UID', 'Original Name','Test Case Name'])
uid='UID-457'
theme = list(bhin[bhin['UID']==uid]['Theme'])[0]
category = list(bhin[bhin['UID']==uid]['Category'])[0]
sub_category = list(bhin[bhin['UID']==uid]['Subcategory'])[0]
entity_type = ['Individual','Vessel']
ofac_list_sampled = ofac_list_dob_mmdy.sample(n = 10)
for index, row in ofac_list_sampled.iterrows():
    original_name = row['name']
    name_pice = row['name'].split(',')
    final_test_name =''
    while len(name_pice)>0:
        n=random.choice(name_pice)
        final_test_name=final_test_name+' '+n
        name_pice.remove(n)
        final_test_name=final_test_name.upper()
    
    final_test_cases.loc[len(final_test_cases)] = [uid, theme, category, sub_category, entity_type[0], uid + ' - ' + str(index), row['uid'], row['name'], final_test_name+' '+row['DOB']] # append to the dataframe

final_test_cases

,UID,Theme,Category,Sub-category,Entity-Type,Test Case ID,OFAC List UID,Original Name,Test Case Name
0,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 9699,35675,"MAKAROV, Vyatscheslav Serafimovich",MAKAROV VYATSCHESLAV SERAFIMOVICH 05/07/55
1,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 260,7167,"FREGOSO AMEZQUITA, Maria Antonieta",FREGOSO AMEZQUITA MARIA ANTONIETA 10/29/52
2,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 322,7256,"KISHK, Samir",SAMIR KISHK 05/14/55
3,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 10978,39680,"PIRI, Morteza",PIRI MORTEZA 07/05/77
4,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 1422,10322,"CASTELLANOS SANCHEZ, Federico Ernesto",FEDERICO ERNESTO CASTELLANOS SANCHEZ 01/11/47
5,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 852,8294,"RUPRAH, Sanjivan Singh",SANJIVAN SINGH RUPRAH 08/09/66
6,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 8366,31124,"KRIVORUCHKO, Aleksei Yurievich",ALEKSEI YURIEVICH KRIVORUCHKO 07/17/75
7,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 462,7662,"BORAVCANIN, Ljubomir",BORAVCANIN LJUBOMIR 02/27/60
8,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 1510,10481,"SOLEIMANI, Qasem",QASEM SOLEIMANI 03/11/57
9,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 7695,28700,"GHASEMZADEH, Mehdi",GHASEMZADEH MEHDI 09/21/81
10,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 4098,18554,"KIM, Kyong Nam",KYONG NAM KIM 07/11/1976
11,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 8605,32231,"DANIEL, Saw",DANIEL SAW 11/25/1957
12,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 8771,33022,"BEDUNKEVICH, Mikhail Petrovich",BEDUNKEVICH MIKHAIL PETROVICH 10/08/1977
13,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 287,7197,"URANGA ARTOLA, Kemen",KEMEN URANGA ARTOLA 05/25/1969
14,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 1871,11470,"SANCHEZ MARTELL, Julio Cesar Jassan Estuardo",SANCHEZ MARTELL JULIO CESAR JASSAN ESTUARDO ...
15,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 2089,11890,"TORRES MARTINEZ, Camilo",CAMILO TORRES MARTINEZ 10/31/1975
16,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 7846,29383,"MAHDAVI, Amin",MAHDAVI AMIN 02/12/1967
17,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 10203,36878,"USATYUK, Valery Petrovich",VALERY PETROVICH USATYUK 07/14/1948
18,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 8606,32232,"MOE, Banyar Aung",BANYAR AUNG MOE 08/14/1947
19,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 2304,12416,"MOLANO TORRES, Deysi Yamile",MOLANO TORRES DEYSI YAMILE 08/23/1986

# UID-458

In [30]:
bhin

,UID,Theme,Category,Subcategory,Entity Type,Example Original Name,Example Test Case Name,Student,Status,Notes,Unnamed: 10,Team Members,Work Allocation
314,UID-315,Names where Name Parts are Modified,Typos,Typo noise name parts,Individual,"Han, Jang Su",JANG SO HAN,Bohao He,complete,"Noise words include but not limited to = [von,...",NaN,NaN,NaN
316,UID-317,Names where Name Parts are Modified,Typos,Very Short Name,Individual,"Bitar, Ahd",AHD BIRAR,Bohao He,complete,NaN,NaN,NaN,NaN
321,UID-322,Special Characters and Spaces,Addition,>2 special characters added,Individual,"Kovtun, Dmitri",DMI&T#RI K!OVTUN,Bohao He,complete,NaN,NaN,NaN,NaN
324,UID-325,Special Characters and Spaces,Addition,1 special character added,Individual,"Liu, Emily",EMILY LIU@,Bohao He,complete,NaN,NaN,NaN,NaN
426,UID-440,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/DD/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/27/1941,Bohao He,complete,NaN,NaN,NaN,NaN
427,UID-441,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/YY,Individual,"Varela, Wilber",WILBER VARELA 11/57,Bohao He,complete,NaN,NaN,NaN,NaN
428,UID-442,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/1941,Bohao He,complete,NaN,NaN,NaN,NaN
429,UID-443,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in YY/DD/MM,Individual,"Varela, Wilber",WILBER VARELA 57/06/11,Bohao He,complete,NaN,NaN,NaN,NaN
430,UID-444,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in DD/MM/YY,Individual,"Varela, Wilber",WILBER VARELA 06/11/59,Bohao He,complete,NaN,NaN,NaN,NaN
431,UID-445,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in DD/MM/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 27/04/1944,Bohao He,complete,NaN,NaN,NaN,NaN
432,UID-446,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD,Individual,"Varela, Wilber",WILBER VARELA 09/06,Bohao He,complete,NaN,NaN,NaN,NaN
433,UID-447,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD/YY,Individual,"Steiger, Jakob",JAKOB STEIGER 09/27/1944,Bohao He,complete,NaN,NaN,NaN,NaN
434,UID-448,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD/YYYY,Individual,"Varela, Wilber",WILBER VARELA 11/06/1959,Bohao He,complete,NaN,NaN,NaN,NaN
435,UID-449,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/YY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/45,Bohao He,complete,NaN,NaN,NaN,NaN
436,UID-450,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/YYYY,Individual,"Varela, Wilber",WILBER VARELA 11/1959,Bohao He,complete,NaN,NaN,NaN,NaN
437,UID-451,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in YY/DD/MM,Individual,"Steiger, Jakob",JAKOB STEIGER 45/27/04,Bohao He,complete,NaN,NaN,NaN,NaN
438,UID-452,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARELA 1955,Bohao He,complete,NaN,NaN,NaN,NaN
439,UID-453,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in DD-MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 27-04-41,Bohao He,complete,NaN,NaN,NaN,NaN
440,UID-454,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in DD-MM-YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 27-04-1941,Bohao He,complete,NaN,NaN,NaN,NaN
441,UID-455,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD,Individual,"Varela, Wilber",WILBER VARRELA 06-11,Bohao He,complete,NaN,NaN,NaN,NaN
442,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-27-41,Bohao He,complete,NaN,NaN,NaN,NaN
443,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-06-1957,Bohao He,complete,NaN,NaN,NaN,NaN
444,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-41,Bohao He,complete,NaN,NaN,NaN,NaN
445,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-1957,Bohao He,complete,NaN,NaN,NaN,NaN
446,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,"Steiger, Jakob",JAKUB STEIGER 41-27-04,Bohao He,complete,NaN,NaN,NaN,NaN
447,UID-461,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1957,Bohao He,complete,NaN,NaN,NaN,NaN
448,UID-462,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in DD-MM-YY,Individual,"Varela, Wilber",WILBER VARRELA 06-11-59,Bohao He,complete,NaN,NaN,NaN,NaN
449,UID-463,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in DD-MM-YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-27-1943,Bohao He,complete,NaN,NaN,NaN,NaN
450,UID-464,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD,Individual,"Varela, Wilber",WILBER VARRELA 09-11,Bohao He,complete,NaN,NaN,NaN,NaN
451,UID-465,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 06-27-43,Bohao He,complete,NaN,NaN,NaN,NaN
452,UID-466,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 9-06-1959,Bohao He,complete,NaN,NaN,NaN,NaN
453,UID-467,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-44,Bohao He,complete,NaN,NaN,NaN,NaN
454,UID-468,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-1959,Bohao He,complete,NaN,NaN,NaN,NaN
455,UID-469,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in YY-DD-MM,Individual,"Steiger, Jakob",JAKUB STEIGER 45-27-04,Bohao He,complete,NaN,NaN,NaN,NaN
456,UID-470,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1959,Bohao He,complete,NaN,NaN,NaN,NaN
457,UID-471,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in DD/MM/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 27/04/43,Bohao He,complete,NaN,NaN,NaN,NaN
458,UID-472,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in DD/MM/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 06/11/1957,Bohao He,complete,NaN,NaN,NaN,NaN
459,UID-473,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD,Individual,"Steiger, Jakob",JAKUB STEIGER 04/27,Bohao He,complete,NaN,NaN,NaN,NaN
460,UID-474,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD/YY,Individual,"Varela, Wilber",WILBER VARRELA 11/06/57,Bohao He,complete,NaN,NaN,NaN,NaN
461,UID-475,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/27/1941,Bohao He,complete,NaN,NaN,NaN,NaN
462,UID-476,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/YY,Individual,"Varela, Wilber",WILBER VARRELA 11/57,Bohao He,complete,NaN,NaN,NaN,NaN
463,UID-477,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/1941,Bohao He,complete,NaN,NaN,NaN,NaN
464,UID-478,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in YY/DD/MM,Individual,"Varela, Wilber",WILBER VARRELA 57/06/11,Bohao He,complete,NaN,NaN,NaN,NaN
465,UID-479,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in DD/MM/YY,Individual,"Varela, Wilber",WILBER VARRELA 06/11/59,Bohao He,complete,NaN,NaN,NaN,NaN
466,UID-480,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in DD/MM/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 27/04/1944,Bohao He,complete,NaN,NaN,NaN,NaN
467,UID-481,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD,Individual,"Varela, Wilber",WILBER VARRELA 09/06,Bohao He,complete,NaN,NaN,NaN,NaN
468,UID-482,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 09/27/1944,Bohao He,complete,NaN,NaN,NaN,NaN
469,UID-483,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11/06/1959,Bohao He,complete,NaN,NaN,NaN,NaN
470,UID-484,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/45,Bohao He,complete,NaN,NaN,NaN,NaN
471,UID-485,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11/1959,Bohao He,complete,NaN,NaN,NaN,NaN
472,UID-486,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in YY/DD/MM,Individual,"Steiger, Jakob",JAKUB STEIGER 45/27/04,Bohao He,complete,NaN,NaN,NaN,NaN
473,UID-487,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1955,Bohao He,complete,NaN,NaN,NaN,NaN
604,UID-639,Negative Control,No Match,100% false match,Individual,"TUFAYLI, Subhi","Anderson, John",Bohao He,NaN,NaN,NaN,NaN,NaN
605,UID-640,Different Name Parts,Title,1 Title difference,Individual,"AL ZAWAHIRI, Dr. Ayman","AL ZAWAHIRI, Mr. Ayman",Bohao He,NaN,NaN,NaN,NaN,NaN
606,UID-641,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in YYYY,Individual,"ANGULO OROBIO (SEGUNDO), Jose Francisco","ANGULO OROBIO (SEGUNDO), Jose Francisco 1964",Bohao He,NaN,NaN,NaN,NaN,NaN

In [31]:
ofac_list_dob_my = ofac_list_dob_mdy[ofac_list_dob_mdy['DOB'].str.count('/')==2]
ofac_list_dob_my['DOB']=ofac_list_dob_my['DOB'].apply(lambda x:x[3:5]+'/'+x[8:])
ofac_list_dob_my

C:\Users\jrblu\AppData\Local\Temp\ipykernel_26244\1603165899.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ofac_list_dob_my['DOB']=ofac_list_dob_my['DOB'].apply(lambda x:x[3:5]+'/'+x[8:])

         uid                                 name entity_type    DOB  count
53      2674                           ABBAS, Abu  individual  12/48      3
54      2675           AL RAHMAN, Shaykh Umar Abd  individual  05/38      3
55      2676               AL ZAWAHIRI, Dr. Ayman  individual  06/51      3
56      2677  AL-ZOMOR, Abboud Abdul Latif Hassan  individual  04/47      3
60      2682          ISLAMBOULI, Mohammad Shawqi  individual  01/55      3
...      ...                                  ...         ...    ...    ...
10974  39676                         FATHI, Murad  individual  05/71      3
10978  39680                        PIRI, Morteza  individual  07/77      3
10989  39694           KHOSRAVI, Mohammad Hossein  individual  09/74      3
10992  39697                    FAZZONE, Gregorio  individual  11/59      3
11000  39710                 OSTAD, Mohammad Reza  individual  06/75      3

[4754 rows x 5 columns]

In [32]:
uid='UID-458'
theme = list(bhin[bhin['UID']==uid]['Theme'])[0]
category = list(bhin[bhin['UID']==uid]['Category'])[0]
sub_category = list(bhin[bhin['UID']==uid]['Subcategory'])[0]
entity_type = ['Individual','Vessel']
ofac_list_sampled = ofac_list_dob_my.sample(n = 10)
for index, row in ofac_list_sampled.iterrows():
    original_name = row['name']
    name_pice = row['name'].split(',')
    final_test_name =''
    while len(name_pice)>0:
        n=random.choice(name_pice)
        final_test_name=final_test_name+' '+n
        name_pice.remove(n)
        final_test_name=final_test_name.upper()
    
    final_test_cases.loc[len(final_test_cases)] = [uid, theme, category, sub_category, entity_type[0], uid + ' - ' + str(index), row['uid'], row['name'], final_test_name+' '+row['DOB']] # append to the dataframe

final_test_cases

,UID,Theme,Category,Sub-category,Entity-Type,Test Case ID,OFAC List UID,Original Name,Test Case Name
0,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 9699,35675,"MAKAROV, Vyatscheslav Serafimovich",MAKAROV VYATSCHESLAV SERAFIMOVICH 05/07/55
1,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 260,7167,"FREGOSO AMEZQUITA, Maria Antonieta",FREGOSO AMEZQUITA MARIA ANTONIETA 10/29/52
2,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 322,7256,"KISHK, Samir",SAMIR KISHK 05/14/55
3,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 10978,39680,"PIRI, Morteza",PIRI MORTEZA 07/05/77
4,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 1422,10322,"CASTELLANOS SANCHEZ, Federico Ernesto",FEDERICO ERNESTO CASTELLANOS SANCHEZ 01/11/47
5,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 852,8294,"RUPRAH, Sanjivan Singh",SANJIVAN SINGH RUPRAH 08/09/66
6,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 8366,31124,"KRIVORUCHKO, Aleksei Yurievich",ALEKSEI YURIEVICH KRIVORUCHKO 07/17/75
7,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 462,7662,"BORAVCANIN, Ljubomir",BORAVCANIN LJUBOMIR 02/27/60
8,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 1510,10481,"SOLEIMANI, Qasem",QASEM SOLEIMANI 03/11/57
9,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 7695,28700,"GHASEMZADEH, Mehdi",GHASEMZADEH MEHDI 09/21/81
10,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 4098,18554,"KIM, Kyong Nam",KYONG NAM KIM 07/11/1976
11,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 8605,32231,"DANIEL, Saw",DANIEL SAW 11/25/1957
12,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 8771,33022,"BEDUNKEVICH, Mikhail Petrovich",BEDUNKEVICH MIKHAIL PETROVICH 10/08/1977
13,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 287,7197,"URANGA ARTOLA, Kemen",KEMEN URANGA ARTOLA 05/25/1969
14,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 1871,11470,"SANCHEZ MARTELL, Julio Cesar Jassan Estuardo",SANCHEZ MARTELL JULIO CESAR JASSAN ESTUARDO ...
15,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 2089,11890,"TORRES MARTINEZ, Camilo",CAMILO TORRES MARTINEZ 10/31/1975
16,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 7846,29383,"MAHDAVI, Amin",MAHDAVI AMIN 02/12/1967
17,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 10203,36878,"USATYUK, Valery Petrovich",VALERY PETROVICH USATYUK 07/14/1948
18,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 8606,32232,"MOE, Banyar Aung",BANYAR AUNG MOE 08/14/1947
19,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 2304,12416,"MOLANO TORRES, Deysi Yamile",MOLANO TORRES DEYSI YAMILE 08/23/1986
20,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 1308,10049,"TARABAIN CHAMAS, Mohamad",TARABAIN CHAMAS MOHAMAD 01/67
21,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 1056,9335,"CORONEL VILLAREAL, Ignacio",IGNACIO CORONEL VILLAREAL 02/54
22,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 9218,34980,"KINAHAN, Christopher Vincent",CHRISTOPHER VINCENT KINAHAN 03/57
23,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 591,7817,"ZIGIC, Zoran",ZIGIC ZORAN 09/58
24,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 5852,23923,"ABDI, Abdifatah Abubakar",ABDI ABDIFATAH ABUBAKAR 04/82
25,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 9018,34180,"ROSIC, Marko",MARKO ROSIC 06/93
26,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 1135,9451,"SALEH, Dr. Abdul Latif",DR. ABDUL LATIF SALEH 03/57
27,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 1073,9354,"AL-TIKRITI, Sa'd Sabawi Ibrahim Hasan",SA'D SABAWI IBRAHIM HASAN AL-TIKRITI 09/88
28,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 10406,37345,"MOSKVICHEV, Evgeny Sergeyevich",EVGENY SERGEYEVICH MOSKVICHEV 09/57
29,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 9454,35430,"MATVEYEV, Mikhail Nikolayevich",MIKHAIL NIKOLAYEVICH MATVEYEV 05/68

# UID-459

In [33]:
ofac_list_dob_myy = ofac_list_dob_mdy[ofac_list_dob_mdy['DOB'].str.count('/')==2]
ofac_list_dob_myy['DOB']=ofac_list_dob_myy['DOB'].apply(lambda x:x[3:5]+'/'+x[6:])
ofac_list_dob_myy

C:\Users\jrblu\AppData\Local\Temp\ipykernel_26244\2715593450.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ofac_list_dob_myy['DOB']=ofac_list_dob_myy['DOB'].apply(lambda x:x[3:5]+'/'+x[6:])

         uid                                 name entity_type      DOB  count
53      2674                           ABBAS, Abu  individual  12/1948      3
54      2675           AL RAHMAN, Shaykh Umar Abd  individual  05/1938      3
55      2676               AL ZAWAHIRI, Dr. Ayman  individual  06/1951      3
56      2677  AL-ZOMOR, Abboud Abdul Latif Hassan  individual  04/1947      3
60      2682          ISLAMBOULI, Mohammad Shawqi  individual  01/1955      3
...      ...                                  ...         ...      ...    ...
10974  39676                         FATHI, Murad  individual  05/1971      3
10978  39680                        PIRI, Morteza  individual  07/1977      3
10989  39694           KHOSRAVI, Mohammad Hossein  individual  09/1974      3
10992  39697                    FAZZONE, Gregorio  individual  11/1959      3
11000  39710                 OSTAD, Mohammad Reza  individual  06/1975      3

[4754 rows x 5 columns]

In [34]:
uid='UID-459'
theme = list(bhin[bhin['UID']==uid]['Theme'])[0]
category = list(bhin[bhin['UID']==uid]['Category'])[0]
sub_category = list(bhin[bhin['UID']==uid]['Subcategory'])[0]
entity_type = ['Individual','Vessel']
ofac_list_sampled = ofac_list_dob_myy.sample(n = 10)
for index, row in ofac_list_sampled.iterrows():
    original_name = row['name']
    name_pice = row['name'].split(',')
    final_test_name =''
    while len(name_pice)>0:
        n=random.choice(name_pice)
        final_test_name=final_test_name+' '+n
        name_pice.remove(n)
        final_test_name=final_test_name.upper()
    
    final_test_cases.loc[len(final_test_cases)] = [uid, theme, category, sub_category, entity_type[0], uid + ' - ' + str(index), row['uid'], row['name'], final_test_name+' '+row['DOB']] # append to the dataframe

final_test_cases

,UID,Theme,Category,Sub-category,Entity-Type,Test Case ID,OFAC List UID,Original Name,Test Case Name
0,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 9699,35675,"MAKAROV, Vyatscheslav Serafimovich",MAKAROV VYATSCHESLAV SERAFIMOVICH 05/07/55
1,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 260,7167,"FREGOSO AMEZQUITA, Maria Antonieta",FREGOSO AMEZQUITA MARIA ANTONIETA 10/29/52
2,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 322,7256,"KISHK, Samir",SAMIR KISHK 05/14/55
3,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 10978,39680,"PIRI, Morteza",PIRI MORTEZA 07/05/77
4,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 1422,10322,"CASTELLANOS SANCHEZ, Federico Ernesto",FEDERICO ERNESTO CASTELLANOS SANCHEZ 01/11/47
5,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 852,8294,"RUPRAH, Sanjivan Singh",SANJIVAN SINGH RUPRAH 08/09/66
6,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 8366,31124,"KRIVORUCHKO, Aleksei Yurievich",ALEKSEI YURIEVICH KRIVORUCHKO 07/17/75
7,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 462,7662,"BORAVCANIN, Ljubomir",BORAVCANIN LJUBOMIR 02/27/60
8,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 1510,10481,"SOLEIMANI, Qasem",QASEM SOLEIMANI 03/11/57
9,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 7695,28700,"GHASEMZADEH, Mehdi",GHASEMZADEH MEHDI 09/21/81
10,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 4098,18554,"KIM, Kyong Nam",KYONG NAM KIM 07/11/1976
11,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 8605,32231,"DANIEL, Saw",DANIEL SAW 11/25/1957
12,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 8771,33022,"BEDUNKEVICH, Mikhail Petrovich",BEDUNKEVICH MIKHAIL PETROVICH 10/08/1977
13,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 287,7197,"URANGA ARTOLA, Kemen",KEMEN URANGA ARTOLA 05/25/1969
14,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 1871,11470,"SANCHEZ MARTELL, Julio Cesar Jassan Estuardo",SANCHEZ MARTELL JULIO CESAR JASSAN ESTUARDO ...
15,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 2089,11890,"TORRES MARTINEZ, Camilo",CAMILO TORRES MARTINEZ 10/31/1975
16,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 7846,29383,"MAHDAVI, Amin",MAHDAVI AMIN 02/12/1967
17,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 10203,36878,"USATYUK, Valery Petrovich",VALERY PETROVICH USATYUK 07/14/1948
18,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 8606,32232,"MOE, Banyar Aung",BANYAR AUNG MOE 08/14/1947
19,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 2304,12416,"MOLANO TORRES, Deysi Yamile",MOLANO TORRES DEYSI YAMILE 08/23/1986
20,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 1308,10049,"TARABAIN CHAMAS, Mohamad",TARABAIN CHAMAS MOHAMAD 01/67
21,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 1056,9335,"CORONEL VILLAREAL, Ignacio",IGNACIO CORONEL VILLAREAL 02/54
22,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 9218,34980,"KINAHAN, Christopher Vincent",CHRISTOPHER VINCENT KINAHAN 03/57
23,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 591,7817,"ZIGIC, Zoran",ZIGIC ZORAN 09/58
24,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 5852,23923,"ABDI, Abdifatah Abubakar",ABDI ABDIFATAH ABUBAKAR 04/82
25,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 9018,34180,"ROSIC, Marko",MARKO ROSIC 06/93
26,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 1135,9451,"SALEH, Dr. Abdul Latif",DR. ABDUL LATIF SALEH 03/57
27,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 1073,9354,"AL-TIKRITI, Sa'd Sabawi Ibrahim Hasan",SA'D SABAWI IBRAHIM HASAN AL-TIKRITI 09/88
28,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 10406,37345,"MOSKVICHEV, Evgeny Sergeyevich",EVGENY SERGEYEVICH MOSKVICHEV 09/57
29,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 9454,35430,"MATVEYEV, Mikhail Nikolayevich",MIKHAIL NIKOLAYEVICH MATVEYEV 05/68
30,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 10178,36853,"RAPOTA, Grigoriy Alexeyevich",RAPOTA GRIGORIY ALEXEYEVICH 02/1944
31,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 2971,15490,"ANDRADE PARRA, Alfredo",ALFREDO ANDRADE PARRA 12/1973
32,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 6704,26093,"AL-QAHTANI, Saud",SAUD AL-QAHTANI 07/1978
33,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 5758,23703,"ABUBAKAR, Abdulpatta Escalon",ABUBAKAR ABDULPATTA ESCALON 03/1965
34,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 706,8091,"BOUYAHIA, Hamadi Ben Abdul Aziz Ben Ali",HAMADI BEN ABDUL AZIZ BEN ALI BOUYAHIA 05/1966
35,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 9672,35648,"KOLESNIK, Andrey Ivanovich",ANDREY IVANOVICH KOLESNIK 02/1960
36,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 4444,19729,"ABDESLAM, Salah",SALAH ABDESLAM 09/1989
37,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 2696,13408,"MONZON ARAUJO, Ofelia",OFELIA MONZON ARAUJO 04/1952
38,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 1739,11240,"ALVAREZ VAZQUEZ, Jose Gerardo",ALVAREZ VAZQUEZ JOSE GERARDO 11/1963
39,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 5042,22012,"HUSAYN, Hanan",HUSAYN HANAN 04/1975

# UID-460

In [35]:
bhin

,UID,Theme,Category,Subcategory,Entity Type,Example Original Name,Example Test Case Name,Student,Status,Notes,Unnamed: 10,Team Members,Work Allocation
314,UID-315,Names where Name Parts are Modified,Typos,Typo noise name parts,Individual,"Han, Jang Su",JANG SO HAN,Bohao He,complete,"Noise words include but not limited to = [von,...",NaN,NaN,NaN
316,UID-317,Names where Name Parts are Modified,Typos,Very Short Name,Individual,"Bitar, Ahd",AHD BIRAR,Bohao He,complete,NaN,NaN,NaN,NaN
321,UID-322,Special Characters and Spaces,Addition,>2 special characters added,Individual,"Kovtun, Dmitri",DMI&T#RI K!OVTUN,Bohao He,complete,NaN,NaN,NaN,NaN
324,UID-325,Special Characters and Spaces,Addition,1 special character added,Individual,"Liu, Emily",EMILY LIU@,Bohao He,complete,NaN,NaN,NaN,NaN
426,UID-440,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/DD/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/27/1941,Bohao He,complete,NaN,NaN,NaN,NaN
427,UID-441,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/YY,Individual,"Varela, Wilber",WILBER VARELA 11/57,Bohao He,complete,NaN,NaN,NaN,NaN
428,UID-442,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/1941,Bohao He,complete,NaN,NaN,NaN,NaN
429,UID-443,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in YY/DD/MM,Individual,"Varela, Wilber",WILBER VARELA 57/06/11,Bohao He,complete,NaN,NaN,NaN,NaN
430,UID-444,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in DD/MM/YY,Individual,"Varela, Wilber",WILBER VARELA 06/11/59,Bohao He,complete,NaN,NaN,NaN,NaN
431,UID-445,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in DD/MM/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 27/04/1944,Bohao He,complete,NaN,NaN,NaN,NaN
432,UID-446,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD,Individual,"Varela, Wilber",WILBER VARELA 09/06,Bohao He,complete,NaN,NaN,NaN,NaN
433,UID-447,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD/YY,Individual,"Steiger, Jakob",JAKOB STEIGER 09/27/1944,Bohao He,complete,NaN,NaN,NaN,NaN
434,UID-448,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD/YYYY,Individual,"Varela, Wilber",WILBER VARELA 11/06/1959,Bohao He,complete,NaN,NaN,NaN,NaN
435,UID-449,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/YY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/45,Bohao He,complete,NaN,NaN,NaN,NaN
436,UID-450,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/YYYY,Individual,"Varela, Wilber",WILBER VARELA 11/1959,Bohao He,complete,NaN,NaN,NaN,NaN
437,UID-451,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in YY/DD/MM,Individual,"Steiger, Jakob",JAKOB STEIGER 45/27/04,Bohao He,complete,NaN,NaN,NaN,NaN
438,UID-452,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARELA 1955,Bohao He,complete,NaN,NaN,NaN,NaN
439,UID-453,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in DD-MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 27-04-41,Bohao He,complete,NaN,NaN,NaN,NaN
440,UID-454,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in DD-MM-YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 27-04-1941,Bohao He,complete,NaN,NaN,NaN,NaN
441,UID-455,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD,Individual,"Varela, Wilber",WILBER VARRELA 06-11,Bohao He,complete,NaN,NaN,NaN,NaN
442,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-27-41,Bohao He,complete,NaN,NaN,NaN,NaN
443,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-06-1957,Bohao He,complete,NaN,NaN,NaN,NaN
444,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-41,Bohao He,complete,NaN,NaN,NaN,NaN
445,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-1957,Bohao He,complete,NaN,NaN,NaN,NaN
446,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,"Steiger, Jakob",JAKUB STEIGER 41-27-04,Bohao He,complete,NaN,NaN,NaN,NaN
447,UID-461,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1957,Bohao He,complete,NaN,NaN,NaN,NaN
448,UID-462,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in DD-MM-YY,Individual,"Varela, Wilber",WILBER VARRELA 06-11-59,Bohao He,complete,NaN,NaN,NaN,NaN
449,UID-463,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in DD-MM-YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-27-1943,Bohao He,complete,NaN,NaN,NaN,NaN
450,UID-464,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD,Individual,"Varela, Wilber",WILBER VARRELA 09-11,Bohao He,complete,NaN,NaN,NaN,NaN
451,UID-465,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 06-27-43,Bohao He,complete,NaN,NaN,NaN,NaN
452,UID-466,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 9-06-1959,Bohao He,complete,NaN,NaN,NaN,NaN
453,UID-467,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-44,Bohao He,complete,NaN,NaN,NaN,NaN
454,UID-468,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-1959,Bohao He,complete,NaN,NaN,NaN,NaN
455,UID-469,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in YY-DD-MM,Individual,"Steiger, Jakob",JAKUB STEIGER 45-27-04,Bohao He,complete,NaN,NaN,NaN,NaN
456,UID-470,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1959,Bohao He,complete,NaN,NaN,NaN,NaN
457,UID-471,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in DD/MM/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 27/04/43,Bohao He,complete,NaN,NaN,NaN,NaN
458,UID-472,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in DD/MM/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 06/11/1957,Bohao He,complete,NaN,NaN,NaN,NaN
459,UID-473,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD,Individual,"Steiger, Jakob",JAKUB STEIGER 04/27,Bohao He,complete,NaN,NaN,NaN,NaN
460,UID-474,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD/YY,Individual,"Varela, Wilber",WILBER VARRELA 11/06/57,Bohao He,complete,NaN,NaN,NaN,NaN
461,UID-475,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/27/1941,Bohao He,complete,NaN,NaN,NaN,NaN
462,UID-476,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/YY,Individual,"Varela, Wilber",WILBER VARRELA 11/57,Bohao He,complete,NaN,NaN,NaN,NaN
463,UID-477,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/1941,Bohao He,complete,NaN,NaN,NaN,NaN
464,UID-478,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in YY/DD/MM,Individual,"Varela, Wilber",WILBER VARRELA 57/06/11,Bohao He,complete,NaN,NaN,NaN,NaN
465,UID-479,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in DD/MM/YY,Individual,"Varela, Wilber",WILBER VARRELA 06/11/59,Bohao He,complete,NaN,NaN,NaN,NaN
466,UID-480,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in DD/MM/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 27/04/1944,Bohao He,complete,NaN,NaN,NaN,NaN
467,UID-481,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD,Individual,"Varela, Wilber",WILBER VARRELA 09/06,Bohao He,complete,NaN,NaN,NaN,NaN
468,UID-482,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 09/27/1944,Bohao He,complete,NaN,NaN,NaN,NaN
469,UID-483,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11/06/1959,Bohao He,complete,NaN,NaN,NaN,NaN
470,UID-484,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/45,Bohao He,complete,NaN,NaN,NaN,NaN
471,UID-485,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11/1959,Bohao He,complete,NaN,NaN,NaN,NaN
472,UID-486,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in YY/DD/MM,Individual,"Steiger, Jakob",JAKUB STEIGER 45/27/04,Bohao He,complete,NaN,NaN,NaN,NaN
473,UID-487,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1955,Bohao He,complete,NaN,NaN,NaN,NaN
604,UID-639,Negative Control,No Match,100% false match,Individual,"TUFAYLI, Subhi","Anderson, John",Bohao He,NaN,NaN,NaN,NaN,NaN
605,UID-640,Different Name Parts,Title,1 Title difference,Individual,"AL ZAWAHIRI, Dr. Ayman","AL ZAWAHIRI, Mr. Ayman",Bohao He,NaN,NaN,NaN,NaN,NaN
606,UID-641,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in YYYY,Individual,"ANGULO OROBIO (SEGUNDO), Jose Francisco","ANGULO OROBIO (SEGUNDO), Jose Francisco 1964",Bohao He,NaN,NaN,NaN,NaN,NaN

In [36]:
ofac_list_dob_ydm = ofac_list_dob_mdy[ofac_list_dob_mdy['DOB'].str.count('/')==2]
ofac_list_dob_ydm['DOB']=ofac_list_dob_ydm['DOB'].apply(lambda x:x[8:]+'/'+x[0:5])
ofac_list_dob_ydm

C:\Users\jrblu\AppData\Local\Temp\ipykernel_26244\1926607375.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ofac_list_dob_ydm['DOB']=ofac_list_dob_ydm['DOB'].apply(lambda x:x[8:]+'/'+x[0:5])

         uid                                 name entity_type       DOB  count
53      2674                           ABBAS, Abu  individual  48/10/12      3
54      2675           AL RAHMAN, Shaykh Umar Abd  individual  38/03/05      3
55      2676               AL ZAWAHIRI, Dr. Ayman  individual  51/19/06      3
56      2677  AL-ZOMOR, Abboud Abdul Latif Hassan  individual  47/19/04      3
60      2682          ISLAMBOULI, Mohammad Shawqi  individual  55/15/01      3
...      ...                                  ...         ...       ...    ...
10974  39676                         FATHI, Murad  individual  71/20/05      3
10978  39680                        PIRI, Morteza  individual  77/05/07      3
10989  39694           KHOSRAVI, Mohammad Hossein  individual  74/23/09      3
10992  39697                    FAZZONE, Gregorio  individual  59/13/11      3
11000  39710                 OSTAD, Mohammad Reza  individual  75/22/06      3

[4754 rows x 5 columns]

In [37]:
uid='UID-460'
theme = list(bhin[bhin['UID']==uid]['Theme'])[0]
category = list(bhin[bhin['UID']==uid]['Category'])[0]
sub_category = list(bhin[bhin['UID']==uid]['Subcategory'])[0]
entity_type = ['Individual','Vessel']
ofac_list_sampled = ofac_list_dob_ydm.sample(n = 10)
for index, row in ofac_list_sampled.iterrows():
    original_name = row['name']
    name_pice = row['name'].split(',')
    final_test_name =''
    while len(name_pice)>0:
        n=random.choice(name_pice)
        final_test_name=final_test_name+' '+n
        name_pice.remove(n)
        final_test_name=final_test_name.upper()
    
    final_test_cases.loc[len(final_test_cases)] = [uid, theme, category, sub_category, entity_type[0], uid + ' - ' + str(index), row['uid'], row['name'], final_test_name+' '+row['DOB']] # append to the dataframe

final_test_cases

,UID,Theme,Category,Sub-category,Entity-Type,Test Case ID,OFAC List UID,Original Name,Test Case Name
0,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 9699,35675,"MAKAROV, Vyatscheslav Serafimovich",MAKAROV VYATSCHESLAV SERAFIMOVICH 05/07/55
1,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 260,7167,"FREGOSO AMEZQUITA, Maria Antonieta",FREGOSO AMEZQUITA MARIA ANTONIETA 10/29/52
2,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 322,7256,"KISHK, Samir",SAMIR KISHK 05/14/55
3,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 10978,39680,"PIRI, Morteza",PIRI MORTEZA 07/05/77
4,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 1422,10322,"CASTELLANOS SANCHEZ, Federico Ernesto",FEDERICO ERNESTO CASTELLANOS SANCHEZ 01/11/47
5,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 852,8294,"RUPRAH, Sanjivan Singh",SANJIVAN SINGH RUPRAH 08/09/66
6,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 8366,31124,"KRIVORUCHKO, Aleksei Yurievich",ALEKSEI YURIEVICH KRIVORUCHKO 07/17/75
7,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 462,7662,"BORAVCANIN, Ljubomir",BORAVCANIN LJUBOMIR 02/27/60
8,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 1510,10481,"SOLEIMANI, Qasem",QASEM SOLEIMANI 03/11/57
9,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,UID-456 - 7695,28700,"GHASEMZADEH, Mehdi",GHASEMZADEH MEHDI 09/21/81
10,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 4098,18554,"KIM, Kyong Nam",KYONG NAM KIM 07/11/1976
11,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 8605,32231,"DANIEL, Saw",DANIEL SAW 11/25/1957
12,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 8771,33022,"BEDUNKEVICH, Mikhail Petrovich",BEDUNKEVICH MIKHAIL PETROVICH 10/08/1977
13,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 287,7197,"URANGA ARTOLA, Kemen",KEMEN URANGA ARTOLA 05/25/1969
14,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 1871,11470,"SANCHEZ MARTELL, Julio Cesar Jassan Estuardo",SANCHEZ MARTELL JULIO CESAR JASSAN ESTUARDO ...
15,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 2089,11890,"TORRES MARTINEZ, Camilo",CAMILO TORRES MARTINEZ 10/31/1975
16,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 7846,29383,"MAHDAVI, Amin",MAHDAVI AMIN 02/12/1967
17,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 10203,36878,"USATYUK, Valery Petrovich",VALERY PETROVICH USATYUK 07/14/1948
18,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 8606,32232,"MOE, Banyar Aung",BANYAR AUNG MOE 08/14/1947
19,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,UID-457 - 2304,12416,"MOLANO TORRES, Deysi Yamile",MOLANO TORRES DEYSI YAMILE 08/23/1986
20,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 1308,10049,"TARABAIN CHAMAS, Mohamad",TARABAIN CHAMAS MOHAMAD 01/67
21,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 1056,9335,"CORONEL VILLAREAL, Ignacio",IGNACIO CORONEL VILLAREAL 02/54
22,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 9218,34980,"KINAHAN, Christopher Vincent",CHRISTOPHER VINCENT KINAHAN 03/57
23,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 591,7817,"ZIGIC, Zoran",ZIGIC ZORAN 09/58
24,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 5852,23923,"ABDI, Abdifatah Abubakar",ABDI ABDIFATAH ABUBAKAR 04/82
25,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 9018,34180,"ROSIC, Marko",MARKO ROSIC 06/93
26,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 1135,9451,"SALEH, Dr. Abdul Latif",DR. ABDUL LATIF SALEH 03/57
27,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 1073,9354,"AL-TIKRITI, Sa'd Sabawi Ibrahim Hasan",SA'D SABAWI IBRAHIM HASAN AL-TIKRITI 09/88
28,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 10406,37345,"MOSKVICHEV, Evgeny Sergeyevich",EVGENY SERGEYEVICH MOSKVICHEV 09/57
29,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,UID-458 - 9454,35430,"MATVEYEV, Mikhail Nikolayevich",MIKHAIL NIKOLAYEVICH MATVEYEV 05/68
30,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 10178,36853,"RAPOTA, Grigoriy Alexeyevich",RAPOTA GRIGORIY ALEXEYEVICH 02/1944
31,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 2971,15490,"ANDRADE PARRA, Alfredo",ALFREDO ANDRADE PARRA 12/1973
32,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 6704,26093,"AL-QAHTANI, Saud",SAUD AL-QAHTANI 07/1978
33,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 5758,23703,"ABUBAKAR, Abdulpatta Escalon",ABUBAKAR ABDULPATTA ESCALON 03/1965
34,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 706,8091,"BOUYAHIA, Hamadi Ben Abdul Aziz Ben Ali",HAMADI BEN ABDUL AZIZ BEN ALI BOUYAHIA 05/1966
35,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 9672,35648,"KOLESNIK, Andrey Ivanovich",ANDREY IVANOVICH KOLESNIK 02/1960
36,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 4444,19729,"ABDESLAM, Salah",SALAH ABDESLAM 09/1989
37,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 2696,13408,"MONZON ARAUJO, Ofelia",OFELIA MONZON ARAUJO 04/1952
38,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 1739,11240,"ALVAREZ VAZQUEZ, Jose Gerardo",ALVAREZ VAZQUEZ JOSE GERARDO 11/1963
39,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,UID-459 - 5042,22012,"HUSAYN, Hanan",HUSAYN HANAN 04/1975
40,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,UID-460 - 10179,36854,"RUKAVISHNIKOVA, Irina Valeryevna",IRINA VALERYEVNA RUKAVISHNIKOVA 73/03/02
41,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,UID-460 - 1533,10570,"KHAYRBIK, Muhammad Nasif",MUHAMMAD NASIF KHAYRBIK 37/05/04
42,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,UID-460 - 6123,24904,"'ABBAS, Yasir",YASIR 'ABBAS 78/22/08
43,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,UID-460 - 9678,35654,"KOTKIN, Sergey Nikolayevich",KOTKIN SERGEY NIKOLAYEVICH 56/11/03
44,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,UID-460 - 8801,33253,"DAMIRCHILU, Mohammad Ali",MOHAMMAD ALI DAMIRCHILU 92/24/05
45,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,UID-460 - 2011,11752,"TASCON ROJAS, Servio Tulio",TASCON ROJAS SERVIO TULIO 38/02/11
46,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,UID-460 - 7686,28691,"AL BEHADILI, Mohammed Saeed Odhafa",AL BEHADILI MOHAMMED SAEED ODHAFA 70/04/03
47,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,UID-460 - 4912,21733,"KANG, Chol Su",CHOL SU KANG 69/13/02
48,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,UID-460 - 1805,11361,"GRIFFIN, Paul Nicholas",GRIFFIN PAUL NICHOLAS 64/16/02
49,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,UID-460 - 4945,21915,"'ALYA, Mazin",'ALYA MAZIN 77/28/02

In [38]:
bhin

,UID,Theme,Category,Subcategory,Entity Type,Example Original Name,Example Test Case Name,Student,Status,Notes,Unnamed: 10,Team Members,Work Allocation
314,UID-315,Names where Name Parts are Modified,Typos,Typo noise name parts,Individual,"Han, Jang Su",JANG SO HAN,Bohao He,complete,"Noise words include but not limited to = [von,...",NaN,NaN,NaN
316,UID-317,Names where Name Parts are Modified,Typos,Very Short Name,Individual,"Bitar, Ahd",AHD BIRAR,Bohao He,complete,NaN,NaN,NaN,NaN
321,UID-322,Special Characters and Spaces,Addition,>2 special characters added,Individual,"Kovtun, Dmitri",DMI&T#RI K!OVTUN,Bohao He,complete,NaN,NaN,NaN,NaN
324,UID-325,Special Characters and Spaces,Addition,1 special character added,Individual,"Liu, Emily",EMILY LIU@,Bohao He,complete,NaN,NaN,NaN,NaN
426,UID-440,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/DD/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/27/1941,Bohao He,complete,NaN,NaN,NaN,NaN
427,UID-441,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/YY,Individual,"Varela, Wilber",WILBER VARELA 11/57,Bohao He,complete,NaN,NaN,NaN,NaN
428,UID-442,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in MM/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/1941,Bohao He,complete,NaN,NaN,NaN,NaN
429,UID-443,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in YY/DD/MM,Individual,"Varela, Wilber",WILBER VARELA 57/06/11,Bohao He,complete,NaN,NaN,NaN,NaN
430,UID-444,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in DD/MM/YY,Individual,"Varela, Wilber",WILBER VARELA 06/11/59,Bohao He,complete,NaN,NaN,NaN,NaN
431,UID-445,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in DD/MM/YYYY,Individual,"Steiger, Jakob",JAKOB STEIGER 27/04/1944,Bohao He,complete,NaN,NaN,NaN,NaN
432,UID-446,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD,Individual,"Varela, Wilber",WILBER VARELA 09/06,Bohao He,complete,NaN,NaN,NaN,NaN
433,UID-447,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD/YY,Individual,"Steiger, Jakob",JAKOB STEIGER 09/27/1944,Bohao He,complete,NaN,NaN,NaN,NaN
434,UID-448,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/DD/YYYY,Individual,"Varela, Wilber",WILBER VARELA 11/06/1959,Bohao He,complete,NaN,NaN,NaN,NaN
435,UID-449,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/YY,Individual,"Steiger, Jakob",JAKOB STEIGER 04/45,Bohao He,complete,NaN,NaN,NaN,NaN
436,UID-450,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in MM/YYYY,Individual,"Varela, Wilber",WILBER VARELA 11/1959,Bohao He,complete,NaN,NaN,NaN,NaN
437,UID-451,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in YY/DD/MM,Individual,"Steiger, Jakob",JAKOB STEIGER 45/27/04,Bohao He,complete,NaN,NaN,NaN,NaN
438,UID-452,IDs,Name and DOB Matching - with slash (/),Exact Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARELA 1955,Bohao He,complete,NaN,NaN,NaN,NaN
439,UID-453,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in DD-MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 27-04-41,Bohao He,complete,NaN,NaN,NaN,NaN
440,UID-454,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in DD-MM-YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 27-04-1941,Bohao He,complete,NaN,NaN,NaN,NaN
441,UID-455,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD,Individual,"Varela, Wilber",WILBER VARRELA 06-11,Bohao He,complete,NaN,NaN,NaN,NaN
442,UID-456,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-27-41,Bohao He,complete,NaN,NaN,NaN,NaN
443,UID-457,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-DD-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-06-1957,Bohao He,complete,NaN,NaN,NaN,NaN
444,UID-458,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-41,Bohao He,complete,NaN,NaN,NaN,NaN
445,UID-459,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in MM-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-1957,Bohao He,complete,NaN,NaN,NaN,NaN
446,UID-460,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YY-DD-MM,Individual,"Steiger, Jakob",JAKUB STEIGER 41-27-04,Bohao He,complete,NaN,NaN,NaN,NaN
447,UID-461,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Exact DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1957,Bohao He,complete,NaN,NaN,NaN,NaN
448,UID-462,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in DD-MM-YY,Individual,"Varela, Wilber",WILBER VARRELA 06-11-59,Bohao He,complete,NaN,NaN,NaN,NaN
449,UID-463,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in DD-MM-YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-27-1943,Bohao He,complete,NaN,NaN,NaN,NaN
450,UID-464,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD,Individual,"Varela, Wilber",WILBER VARRELA 09-11,Bohao He,complete,NaN,NaN,NaN,NaN
451,UID-465,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 06-27-43,Bohao He,complete,NaN,NaN,NaN,NaN
452,UID-466,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-DD-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 9-06-1959,Bohao He,complete,NaN,NaN,NaN,NaN
453,UID-467,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04-44,Bohao He,complete,NaN,NaN,NaN,NaN
454,UID-468,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in MM-YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11-1959,Bohao He,complete,NaN,NaN,NaN,NaN
455,UID-469,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in YY-DD-MM,Individual,"Steiger, Jakob",JAKUB STEIGER 45-27-04,Bohao He,complete,NaN,NaN,NaN,NaN
456,UID-470,IDs,Name and DOB Matching - With Hyphen (-),Fuzzy Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1959,Bohao He,complete,NaN,NaN,NaN,NaN
457,UID-471,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in DD/MM/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 27/04/43,Bohao He,complete,NaN,NaN,NaN,NaN
458,UID-472,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in DD/MM/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 06/11/1957,Bohao He,complete,NaN,NaN,NaN,NaN
459,UID-473,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD,Individual,"Steiger, Jakob",JAKUB STEIGER 04/27,Bohao He,complete,NaN,NaN,NaN,NaN
460,UID-474,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD/YY,Individual,"Varela, Wilber",WILBER VARRELA 11/06/57,Bohao He,complete,NaN,NaN,NaN,NaN
461,UID-475,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/DD/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/27/1941,Bohao He,complete,NaN,NaN,NaN,NaN
462,UID-476,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/YY,Individual,"Varela, Wilber",WILBER VARRELA 11/57,Bohao He,complete,NaN,NaN,NaN,NaN
463,UID-477,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in MM/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/1941,Bohao He,complete,NaN,NaN,NaN,NaN
464,UID-478,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Exact DOB in YY/DD/MM,Individual,"Varela, Wilber",WILBER VARRELA 57/06/11,Bohao He,complete,NaN,NaN,NaN,NaN
465,UID-479,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in DD/MM/YY,Individual,"Varela, Wilber",WILBER VARRELA 06/11/59,Bohao He,complete,NaN,NaN,NaN,NaN
466,UID-480,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in DD/MM/YYYY,Individual,"Steiger, Jakob",JAKUB STEIGER 27/04/1944,Bohao He,complete,NaN,NaN,NaN,NaN
467,UID-481,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD,Individual,"Varela, Wilber",WILBER VARRELA 09/06,Bohao He,complete,NaN,NaN,NaN,NaN
468,UID-482,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 09/27/1944,Bohao He,complete,NaN,NaN,NaN,NaN
469,UID-483,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/DD/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11/06/1959,Bohao He,complete,NaN,NaN,NaN,NaN
470,UID-484,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/YY,Individual,"Steiger, Jakob",JAKUB STEIGER 04/45,Bohao He,complete,NaN,NaN,NaN,NaN
471,UID-485,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in MM/YYYY,Individual,"Varela, Wilber",WILBER VARRELA 11/1959,Bohao He,complete,NaN,NaN,NaN,NaN
472,UID-486,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in YY/DD/MM,Individual,"Steiger, Jakob",JAKUB STEIGER 45/27/04,Bohao He,complete,NaN,NaN,NaN,NaN
473,UID-487,IDs,Name and DOB Matching - with slash (/),Fuzzy Name and Out of range DOB in YYYY,Individual,"Varela, Wilber",WILBER VARRELA 1955,Bohao He,complete,NaN,NaN,NaN,NaN
604,UID-639,Negative Control,No Match,100% false match,Individual,"TUFAYLI, Subhi","Anderson, John",Bohao He,NaN,NaN,NaN,NaN,NaN
605,UID-640,Different Name Parts,Title,1 Title difference,Individual,"AL ZAWAHIRI, Dr. Ayman","AL ZAWAHIRI, Mr. Ayman",Bohao He,NaN,NaN,NaN,NaN,NaN
606,UID-641,IDs,Name and DOB Matching - with slash (/),Exact Name and Exact DOB in YYYY,Individual,"ANGULO OROBIO (SEGUNDO), Jose Francisco","ANGULO OROBIO (SEGUNDO), Jose Francisco 1964",Bohao He,NaN,NaN,NaN,NaN,NaN

In [39]:
final_test_cases.to_csv('bhin7.csv')